OPT = -sas -m 

.as.at:
	otr64 $(OPT) $*
	ao64 -l$(@B).tc $@

rests.at: rests.as 
restc.at: restc.as 
edic.at: edic.as 
qedi.at: qedi.as 
qocci.at: qocci.as 
qocciedi.at: qocciedi.as 

! make

qtc.at: qtc.as
qsi.at: qsi.as
qsilv.at: qsilv.as
qmc.at: qmc.as
qbd.at: qbd.as
join.at: join.as


! make
