/* File generated by /home/abal64/bin/linbda Version 2.1a.0.03 : /home/abal64/src/z/z.def -> /home/abal64/src/z/z.c */
#ifndef __linbda__home_abal64_src_z_z_c__
#define __linbda__home_abal64_src_z_z_c__
#include <stdio.h>
#include <setjmp.h>
#include "ldfbda.h"

private BDA * DynamicLibrary;
	public  LPBDA_INIT	rt_init;
	public  BDA_INIT	v_rt_init;
	public  BDA_ARG rt_arg;

/* ABAL Runtime Error Trap */
private	jmp_buf rt_error_context;
public  VOID rt_error(EXAWORD evalue) { 
	longjmp(rt_error_context,evalue);
	return;
}

private int function_counter=0;
/* ABAL Word Conversions */
public EXAWORD GetAbalInt8(char FAR PTR bptr)
{
	return(*bptr);
}

public EXAWORD GetAbalInt16(BYTE FAR PTR wptr)
{
	return(((*wptr<< 8)|*(wptr+1)));
}

public EXAWORD GetAbalInt32(BYTE FAR PTR wptr)
{
	int length=4;
	EXAWORD result=0;
	while ( length-- ) result = ((result << 8) | (*(wptr++) & 0x00FF));
	return(result);
}

public EXAWORD GetAbalInt64(BYTE FAR PTR wptr)
{
	int length=8;
	EXAWORD result=0;
	while ( length-- ) result = ((result << 8) | (*(wptr++) & 0x00FF));
	return(result);
}

public void PutAbalInt8(char FAR * wptr, EXAWORD v)
{
	*wptr = (v & 0x00FF);
	return;
}
public void PutAbalInt16(BYTE FAR * wptr, EXAWORD v)
{
	int length=2;
	while ( length-- ) { *(wptr +length) = (v & 0x00FF); v >>= 8; }
	return;
}

public void PutAbalInt32(BYTE FAR * wptr, EXAWORD v)
{
	int length=4;
	while ( length-- ) { *(wptr +length) = (v & 0x00FF); v >>= 8; }
	return;
}

public void PutAbalInt64(BYTE FAR * wptr, EXAWORD v)
{
	int length=8;
	while ( length-- ) { *(wptr +length) = (v & 0x00FF); v >>= 8; }
	return;
}

#define LdfParaWord(n) (tptr[n]==1 ? GetAbalInt16(pptr[n]) : (tptr[n]==0 ? GetAbalInt8(pptr[n]) : (tptr[n]==5 ? GetAbalInt32(pptr[n]): GetAbalInt64(pptr[n]) )))
#define LdfParaByte(n) (tptr[n]==1 ? (GetAbalInt16(pptr[n])&0x00FF) : (tptr[n]==0 ? GetAbalInt8(pptr[n]):(tptr[n]==5?(GetAbalInt32(pptr[n])&0x00FF):(GetAbalInt64(pptr[n])&0x00FF))))
/* Library Information */
public EXAWORD LdfBdaInformation(void * vptr)
{
	printf(
		"\n   Abal Dynamic Library : Z64.Abal.3.3u.0.01"
		);
	printf(
		"\n   Copyright (c) Amenesik / Sologic \n\n"
		);
	return(0);
}

/* Library Destructor */
public EXAWORD LdfBdaTerminate()
{
	if (DynamicLibrary->fin != (VOID (FAR PTR)()) 0)
		 (*DynamicLibrary->fin)();
	return(0);
}

/* Library Call Through */
public EXAWORD LdfBdaExecute(
	EXAWORD fid,
	EXAWORD argc,
	BYTE FAR tptr[],
	VOID FAR PTR FAR pptr[],
	EXAWORD FAR wptr[],
	int FAR * eptr)
{
	EXAWORD	result=0;
	rt_arg.c=argc; rt_arg.v=pptr;
	rt_arg.l=wptr; rt_arg.t=tptr;
	if ((result=setjmp(rt_error_context))!=0) {
		if ( eptr != (int FAR *) 0) *eptr = result;
		return( result );
		}
	/* version = 1 */
	/* runtime = "z" */
	/* %zzinit($) */
	/* %zzinitmouse($) */
	/* zzshowmouse() */
	/* zzhidemouse() */
	/* zzreserve1() */
	/* zzstatusmouse($) */
	/* zzreserve2() */
	/* zzreserve3() */
	/* %zrlecpt($,$,%) */
	/* %zrledcpt($,$,%) */
	/* zzreserve4() */
	/* zzreserve5() */
	/* zzreserve6() */
	/* zzreserve7() */
	/* zbprint(%,$,%,%) */
	/* zbprintxy(%,%,%,$) */
	/* zbhide(%) */
	/* zbshow(%,%,%,%,%) */
	/* zzwait1_10() */
	/* %zwanal($,%,%,%?,%?,%?,%?,%?) */
	/* zzend() */
	/* zz_adrs($) */
	/* %zzpush(%,%,%,%,%) */
	/* %zzpop() */
	/* %zzwmove(%,%) */
	/* zzshadow(%,%,%,%)  */
	/* %zscroll(%,%,%,%,%,%) */
	/* azac_init(%) */
	/* %azac_open(%,$,%) */
	/* %azac_nextline(%,$,%?) */
	/* %azac_prevline(%,$,%?) */
	/* %azac_firstline(%,$,%?) */
	/* %azac_lastline(%,$,%?) */
	/* azac_close(%) */
	/* %azac_create(%,$) */
	/* %azac_write(%,$,%) */
	/* zbprintvar(%,%,%,$) */
	/* zbprintitem(%,%,%,$,$,%,%,%) */
	/* zprintran(%,$) */
	/* %ztab_2_seq(%,%,$,$,$,%,%,$,$,%) */
	/* %zstring_cpt($,%,$) */
	/* %zzfind($,$,%,%) */
	/* %azac_read(%,$,%) */
	/* %zindex($,#,%,%) */
	/* zoem2ansi($,%) */
	/* zansi2oem($,%) */
	/* %zwinhelp($,%,$?) */
	/* zzreserve16() */
	/* zzreserve17() */
	/* zzreserve18() */
	/* zwin_mesval($,%) */
	/* zwin_messerr($,%) */
	/* %zwin_mesyesno($,%,%) */
	/* %zwin_mesync($,%) */
	/* zwin_button(%,%,%,%,%,$,%,$) */
	/* zwin_smallbutton(%,%,%,%,$,%,$) */
	/* zwin_F1button(%,%,%) */
	/* %zwin_vlift(%,%,%,%,%,%,%) */
	/* zwin_lisf_lift(%,%,%,%,%) */
	/* zwin_frame(%,%,%,%,%,%,%,%,$) */
	/* zwin_window(%,%,%,%,%,%,%,$,%,%) */
	/* %zwin_font(%) */
	/* zwin_check(%,%,%,%,%,%) */
	/* zwin_radio(%,%,%,%,%,%) */
	/* zwin_statusxy(%,%) */
	/* zwin_status_draw() */
	/* zwin_status($,%) */
	/* zwin_mousecursor(%) */
	/* zwin_askcursor(%) */
	/* %zwin_bbitmap(%,$,$,%) */
	/* %zwin_bitmap($,%,%,%,%) */
	/* zwin_actual(%,%,%,%) */
	/* %zwdll_load($) */
	/* zwdll_free() */
	/* zwin_hlift(%,%,%,%,%,%,%) */
	/* %zwin_alone($) */
	/* %zchdir($) */
	/* %zwbmp_load(%,$,%) */
	/* zwbmp_free(%) */
	/* %zwin_bbmp(%,$,%,%) */
	/* %zwin_bmp(%,%,%,%,%) */
	/* %zzwin_version() */
	/* zzwin_clear($,%,%,%,%) */
	/* zzprint_title(%,%,%,$) */
	/* zzwinmove(%,%,%,%,%,%) */
	/* zzwinmoveable(%,%,%,%) */
	/* zwin_tabview(%,%,%,%,%,$,%,$) */
	/* zzgetmaxy(%?,%?) */
	/* %zzfont_choose($) */
	/* %zzfont_create(%,$) */
	/* zzfont_delete(%) */
	/* zzwin_title(%,%,%,$,%,%,%) */
	/* zzprintl(%,$,%) */
	/* %zzw_getcolor(%,%) */
	/* zzw_color(%,%,%) */
	/* zzw_brush(%,%,%,%) */
	/* zzw_pen(%,%,%,%,%) */
	/* zzw_point(%,%) */
	/* zzw_line(%,%,%,%) */
	/* zzw_rectangle(%,%,%,%) */
	/* zzw_roundrect(%,%,%,%,%,%) */
	/* zzw_ellipse(%,%,%,%) */
	/* zzw_pie(%,%,%,%,%,%,%,%) */
	/* zzw_trapez(%,%,%,%,%,%,%,%) */
	/* zzw_printxy(%,%,%,$) */
	/* %zwin_xbmp(%,%,%,%,%,%,%) */
	/* %zzwin_nbbits() */
	/* zzdefault_font(%,%) */
	/* zzRGBcolor(%,%,%,%,%) */
	/* zzdefault_color(%,%,%,%) */
	/* zwin_vabutton(%,%,%) */
	/* zzwin_setpile(%,%,%,%,%,%) */
	/* %zsystem_menu() */
	/* zzreserve39() */
	/* zTraMsg(%,%,$,$) */
	/* zTraMsgInt(%,%,$,$,%) */
	/* %zPrlTst1(%) */
	/* %zPrlTst2(%) */
	/* %zPrlTst3(%) */
	/* %zManageLoadgo(%) */
	/* %zScreenSaver() */
	/* zTraDump(%,%,$,$,$,%) */
	/* zzreserve48() */
	/* zzreserve49() */
	/* zzreserve50() */
	/* zzreserve51() */
	/* zzreserve52() */
	/* zzreserve53() */
	/* zzreserve54() */
	/* zzreserve55() */
	/* zzreserve56() */
	/* zzreserve57() */
	/* zzreserve58() */
	/* zzreserve59() */
	/* zzreserve60() */
	/* zzreserve61() */
	/* zzreserve62() */
	/* zzreserve63() */
	/* zzreserve64() */
	/* zzreserve65() */
	/* zzreserve66() */
	/* zzreserve67() */
	/* zzreserve68() */
	/* zzreserve69() */
	/* zzreserve70() */
	/* zzreserve71() */
	/* zzreserve72() */
	/* zzreserve73() */
	/* zzreserve74() */
	/* zzreserve75() */
	/* zzreserve76() */
	/* zzreserve77() */
	/* zzreserve78() */
	/* zzreserve79() */
	/* zzreserve80() */
	/* zzreserve81() */
	/* zzreserve82() */
	/* zzreserve83() */
	/* zzreserve84() */
	/* zzreserve85() */
	/* zzreserve86() */
	/* zzreserve87() */
	/* zzreserve88() */
	/* zzreserve89() */
	/* zzreserve90() */
	/* zzreserve91() */
	/* zzreserve92() */
	/* zzreserve93() */
	/* zzreserve94() */
	/* zzreserve95() */
	/* zzreserve96() */
	/* zzreserve97() */
	/* zzreserve98() */
	/* zzreserve99() */
	if (fid > function_counter) result=138; else result=(*DynamicLibrary->fonction[fid])(pptr);
	/* end */
	return(result);
}

/* Library Constructor */

public EXAWORD LdfBdaInitialise(
	BDA_INIT FAR PTR descriptor,
	EXAWORD dlength)
{
	int	i=0;
	rt_init = descriptor;
	function_counter=174;
	if (!(DynamicLibrary = InitRelais()))
		return(139);
	else	return(0);
}

#endif  /* __linbda__home_abal64_src_z_z_c__ */
/* End of File */
