/* File generated by /opt/prologue/bin/linbda Version 1.1b.0.06 : /home/Dev/abal32/src/tty/tty.def -> /home/Dev/abal32/src/tty/tty.c */
#ifndef __linbda__home_Dev_abal32_src_tty_tty_c__
#define __linbda__home_Dev_abal32_src_tty_tty_c__
#include <stdio.h>
#include <setjmp.h>
#include "ldfbda.h"

static BDA * DynamicLibrary;
	LPBDA_INIT	rt_init;
	BDA_INIT	v_rt_init;
	BDA_ARG rt_arg;

/* ABAL Runtime Error Trap */
static jmp_buf rt_error_context;
VOID rt_error(EXAWORD evalue) { 
	longjmp(rt_error_context,evalue);
	return;
}

static int function_counter=0;
/* ABAL Word Convertor */
static EXAWORD LdfAbalByte(char FAR PTR bptr)
{
	return(*bptr);
}

static EXAWORD LdfAbalWord(BYTE FAR PTR wptr)
{
	return(((*wptr<< 8) | *(wptr+1)));
}

static EXAWORD LdfAbalLong(BYTE FAR PTR wptr)
{
	return((((*wptr)<< 24) | (*(wptr+1) << 16)  | (*(wptr+2) << 8)| *(wptr+3)));
}

#define LdfParaWord(n) ( tptr[n] == 1 ? LdfAbalWord(pptr[n]) : ( tptr[n] == 0 ?  LdfAbalByte(pptr[n]) : LdfAbalLong(pptr[n])) )
#define LdfParaByte(n) ( tptr[n] == 1 ? (LdfAbalWord(pptr[n])&0x00FF) : ( tptr[n] == 0 ?  LdfAbalByte(pptr[n]) : (LdfAbalLong(pptr[n])&0x00FF) ) )

static BYTE PTR function_names[256];
static char * trace_name=(char*)0;
static FILE * trace_handle=(FILE*)0;
extern long time(long*);

/* Trace Activation */
static void start_trace()
{
	trace_name = getenv("TRACE_TTY");
	if ( trace_name != (char *) 0 ) {
		trace_handle=fopen(trace_name,"w");
		}
	return;
}

/* Trace Write */
static void write_trace(char * mptr)
{
	if ( trace_handle != (FILE*)0) {
		fprintf(trace_handle,mptr);
		fprintf(trace_handle,"\r\n");
		}
	return;
}

/* Trace Result */
static void trace_result(EXAWORD result)
{
	if ( trace_handle != (FILE*)0) {
		fprintf(trace_handle,"RETURN: %u \r\n",result);
		}
	return;
}

/* Trace Call */
static void trace_call(
	EXAWORD fid,
	EXAWORD argc,
	BYTE FAR tptr[],
	VOID FAR PTR FAR pptr[],
	EXAWORD FAR wptr[])
{
	char * bptr;
	int	i=0;
	int	j=0;
	if ( trace_handle != (FILE*)0) {
			fprintf(trace_handle,"[%lu] ",time((long*)0));
		if ( function_names[fid] != (char *) 0) {
			fprintf(trace_handle,"(%s)",function_names[fid]);
			}
		else	{
			fprintf(trace_handle,"(call %u)",fid);
			}
		for (i=0; i < argc; i++) {
			switch(tptr[i]) {
				case 0x0080 : 
					fprintf(trace_handle,"\t(*b=%x)\r\n",*((bptr=pptr[i])));
					break;
				case 0  : 
					fprintf(trace_handle,"\t(b=%x)\r\n",*((bptr=pptr[i])));
					break;
				case 0x0081 : 
					fprintf(trace_handle,"\t(*w=%x)\r\n",LdfAbalWord(pptr[i]));
					break;
				case 1  : 
					fprintf(trace_handle,"\t(w=%x)\r\n",LdfAbalWord(pptr[i]));
					break;
				case 2  : 
				case 3  : 
				case 0x0082 : 
				case 0x0083 : 
					fprintf(trace_handle,"\t(*=");
					for (bptr=pptr[i],j=0;j<wptr[i];j++) {
						fprintf(trace_handle,"%x ",(*(bptr+j)&0x00FF));
						if ((j % 20) == 19) {
							fprintf(trace_handle,"\r\n");
							}
						}
					fprintf(trace_handle,")\r\n");
				};
			}
		fprintf(trace_handle,"\r\n");
		}
	return;
}

/* Trace Closure */
static void close_trace()
{
	if ( trace_handle != (FILE*)0) {
		fclose(trace_handle);
		trace_handle=(FILE*)0;
		}
	return;
}

/* Library Information */
EXAWORD LdfBdaInformation(void * vptr)
{
	printf(
		"\n   Abal Dynamic Library : unspecified"
		);
	printf(
		"\n   Copyright (c) 2006 Amenesik / Sologic \n\n"
		);
	return(0);
}

/* Library Destructor */
EXAWORD LdfBdaTerminate()
{
	write_trace("LdfBdaTerminate()");
	close_trace();
	if (DynamicLibrary->fin != (VOID (FAR PTR)()) 0)
		 (*DynamicLibrary->fin)();
	return(0);
}

/* Library Call Through */
EXAWORD LdfBdaExecute(
	EXAWORD fid,
	EXAWORD argc,
	BYTE FAR tptr[],
	VOID FAR PTR FAR pptr[],
	EXAWORD FAR wptr[],
	EXAWORD FAR * eptr)
{
	EXAWORD	result=0;
	rt_arg.c=argc; rt_arg.v=pptr;
	rt_arg.l=wptr; rt_arg.t=tptr;
	if ((result=setjmp(rt_error_context))!=0) {
		if ( eptr != (EXAWORD FAR *) 0) *eptr = result;
		return( result );
		}
	if ( trace_handle != (FILE*)0) {
	trace_call(fid,argc,tptr,pptr,wptr);
		}
	/* version = 1 */
	/* Runtime = "tty" */
	/* % ttyopen(%?,$) */
	/* % ttyclose(%) */
	/* % ttyconnect(%,.) */
	/* % ttydcn(%) */
	/* % ttywrite(%,#,$,.) */
	/* % ttyread(%,$?,.) */
	/* % ttybreak(%) */
	/* % ttybuffer(%,%) */
	if (fid > function_counter) result=138; else result=(*DynamicLibrary->fonction[fid])(pptr);
	/* End */
	if ( trace_handle != (FILE*)0) {
		trace_result( result );
	trace_call(fid,argc,tptr,pptr,wptr);
		}
	return(result);
}

/* Library Constructor */

EXAWORD LdfBdaInitialise(
	BDA_INIT FAR PTR descriptor,
	EXAWORD dlength)
{
	int	i=0;
	rt_init = descriptor;
	function_counter=8;
	function_names[0] = "% ttyopen(%?,$)";
	function_names[1] = "% ttyclose(%)";
	function_names[2] = "% ttyconnect(%,.)";
	function_names[3] = "% ttydcn(%)";
	function_names[4] = "% ttywrite(%,#,$,.)";
	function_names[5] = "% ttyread(%,$?,.)";
	function_names[6] = "% ttybreak(%)";
	function_names[7] = "% ttybuffer(%,%)";
	start_trace();
	write_trace("LdfBdaInitialise()");
	if (!(DynamicLibrary = InitRelais()))
		return(139);
	else	return(0);
}

#endif  /* __linbda__home_Dev_abal32_src_tty_tty_c__ */
/* End of File */
