/* File generated by /home/abal64/bin/linbda Version 2.1a.0.03 : /home/abal64/src/fac/fac.def -> /home/abal64/src/fac/fac.c */
#ifndef __linbda__home_abal64_src_fac_fac_c__
#define __linbda__home_abal64_src_fac_fac_c__
#include <stdio.h>
#include <setjmp.h>
#include "ldfbda.h"

private BDA * DynamicLibrary;
	public  LPBDA_INIT	rt_init;
	public  BDA_INIT	v_rt_init;
	public  BDA_ARG rt_arg;

/* ABAL Runtime Error Trap */
private	jmp_buf rt_error_context;
public  VOID rt_error(EXAWORD evalue) { 
	longjmp(rt_error_context,evalue);
	return;
}

private int function_counter=0;
/* ABAL Word Conversions */
public EXAWORD GetAbalInt8(char FAR PTR bptr)
{
	return(*bptr);
}

public EXAWORD GetAbalInt16(BYTE FAR PTR wptr)
{
	return(((*wptr<< 8)|*(wptr+1)));
}

public EXAWORD GetAbalInt32(BYTE FAR PTR wptr)
{
	int length=4;
	EXAWORD result=0;
	while ( length-- ) result = ((result << 8) | (*(wptr++) & 0x00FF));
	return(result);
}

public EXAWORD GetAbalInt64(BYTE FAR PTR wptr)
{
	int length=8;
	EXAWORD result=0;
	while ( length-- ) result = ((result << 8) | (*(wptr++) & 0x00FF));
	return(result);
}

public void PutAbalInt8(char FAR * wptr, EXAWORD v)
{
	*wptr = (v & 0x00FF);
	return;
}
public void PutAbalInt16(BYTE FAR * wptr, EXAWORD v)
{
	int length=2;
	while ( length-- ) { *(wptr +length) = (v & 0x00FF); v >>= 8; }
	return;
}

public void PutAbalInt32(BYTE FAR * wptr, EXAWORD v)
{
	int length=4;
	while ( length-- ) { *(wptr +length) = (v & 0x00FF); v >>= 8; }
	return;
}

public void PutAbalInt64(BYTE FAR * wptr, EXAWORD v)
{
	int length=8;
	while ( length-- ) { *(wptr +length) = (v & 0x00FF); v >>= 8; }
	return;
}

#define LdfParaWord(n) (tptr[n]==1 ? GetAbalInt16(pptr[n]) : (tptr[n]==0 ? GetAbalInt8(pptr[n]) : (tptr[n]==5 ? GetAbalInt32(pptr[n]): GetAbalInt64(pptr[n]) )))
#define LdfParaByte(n) (tptr[n]==1 ? (GetAbalInt16(pptr[n])&0x00FF) : (tptr[n]==0 ? GetAbalInt8(pptr[n]):(tptr[n]==5?(GetAbalInt32(pptr[n])&0x00FF):(GetAbalInt64(pptr[n])&0x00FF))))
/* Library Information */
public EXAWORD LdfBdaInformation(void * vptr)
{
	printf(
		"\n   Abal Dynamic Library : FAC64.Abal.3.3u.0.01"
		);
	printf(
		"\n   Copyright (c) Amenesik / Sologic \n\n"
		);
	return(0);
}

/* Library Destructor */
public EXAWORD LdfBdaTerminate()
{
	if (DynamicLibrary->fin != (VOID (FAR PTR)()) 0)
		 (*DynamicLibrary->fin)();
	return(0);
}

/* Library Call Through */
public EXAWORD LdfBdaExecute(
	EXAWORD fid,
	EXAWORD argc,
	BYTE FAR tptr[],
	VOID FAR PTR FAR pptr[],
	EXAWORD FAR wptr[],
	int FAR * eptr)
{
	EXAWORD	result=0;
	rt_arg.c=argc; rt_arg.v=pptr;
	rt_arg.l=wptr; rt_arg.t=tptr;
	if ((result=setjmp(rt_error_context))!=0) {
		if ( eptr != (int FAR *) 0) *eptr = result;
		return( result );
		}
	/* Version = 1 */
	/* Runtime = "fac" */
	/* % StrmOpen(%,$,%) */
	/* % StrmClose(%) */
	/* % StrmFlush(%) */
	/* % StrmGetError(%) */
	/* % StrmClearError(%) */
	/* % StrmReadByte(%,#?) */
	/* % StrmWriteByte(%,#) */
	/* % StrmReadBuf(%,$?,%,%?) */
	/* % StrmWriteBuf(%,$,%,%?) */
	/* % StrmFindByte(%,#,%) */
	/* % StrmFindBuf(%,$,%,%) */
	/* % StrmFindByteInColl(%,$,%,#?,%) */
	/* % StrmSeek(%,%,%) */
	/* % StrmSeek_BCD(%,*,%) */
	/* % StrmTell(%,%?) */
	/* % StrmTell_BCD(%,*?) */
	/* % StrmFileSize(%,%?) */
	/* % StrmFileSize_BCD(%,*?) */
	/* % StrmEof(%) */
	/* % StrmLnAnalyse(%) */
	/* % StrmLnRead(%,$?,%,%?) */
	/* % StrmLnAppend(%,$,%,%?) */
	/* % StrmLnSeek(%,%,%) */
	/* % StrmLnSeek_BCD(%,*,%) */
	/* % StrmLnTell(%,%?) */
	/* % StrmLnTell_BCD(%,*?) */
	/* % StrmLnFileSize(%,%?) */
	/* % StrmLnFileSize_BCD(%,*?) */
	/* % StrmLnEof(%) */
	/* % StrmLnLen(%,%?) */
	/* % StrmLnLen_BCD(%,*?) */
	/* % StrmLnSetTab(%,%) */
	/* % StrmLnGetTab(%,%?) */
	/* % StrmLnFileFormat(%,%?,%?) */
	/* % StrmLnInfoLine(%,%?,%?) */
	/* % StrmLnInfoLine_BCD(%,*?,*?) */
	/* % StrmLnIsLast(%) */
	/* % StrmLnMaxLen(%,%?) */
	/* % StrmLnMaxLen_BCD(%,*?) */
	/* % FileGetVersion($,$?,%,%?) */
	/* % FileCopy($,$,%) */
	/* % FileCopyExt($,$,%,%,%) */
	/* % FileCopyExt_BCD($,$,%,*,*) */
	/* % FileComp($,$,%,%?) */
	/* % FileComp_BCD($,$,%,*?) */
	/* % FileSize($,%,%?) */
	/* % FileSize_BCD($,%,*?) */
	/* % SysMkDir($,%) */
	/* % SysRmDir($) */
	/* % SysNgfUpd($) */
	/* % StrmLnSetPad(%,%) */
	/* % StrmLnGetPad(%,%?) */
	/* % StrmGetFree(%?) */
	/* % StrmReadChar(%,$?) */
	/* % StrmWriteChar(%,$)  */
	/* % StrmLnReadSec(%,$?,%,%?) */
	/* % StrmLnReadKey(%,$?,%,%?,$?,%,%?) */
	/* % StrmLnFindSec(%,$,%,%) */
	/* % StrmLnFindKey(%,$,%,$?,%,%?,%) */
	/* % FileIniFind($,$,%,$,%,$,%,%?) */
	/* % SysGetAbalEnv($,$,%,%?) */
	/* % StrmFindChar(%,$,%) */
	/* % StrmLnSetFormFeed(%,%) */
	/* % StrmLnGetFormFeed(%,%?) */
	/* % StrmFindCharInColl(%,$,%,$?,%) */
	if (fid > function_counter) result=138; else result=(*DynamicLibrary->fonction[fid])(pptr);
	/* end */
	return(result);
}

/* Library Constructor */

public EXAWORD LdfBdaInitialise(
	BDA_INIT FAR PTR descriptor,
	EXAWORD dlength)
{
	int	i=0;
	rt_init = descriptor;
	function_counter=65;
	if (!(DynamicLibrary = InitRelais()))
		return(139);
	else	return(0);
}

#endif  /* __linbda__home_abal64_src_fac_fac_c__ */
/* End of File */
