! shell cd $(ABAL)/exa64; $(MAKE)
! error thats all
! shell cd $(ABAL)/exa36; $(MAKE)
! shell cd $(ABAL)/exa38; $(MAKE)
! shell cd $(ABAL)/exa37; $(MAKE)
! shell cd $(ABAL)/exa40; $(MAKE)
! shell cd $(ABAL)/exa41; $(MAKE)
#! shell cd $(ABAL)/exa16; $(MAKE)

