! include ut.mf
! make
! include gm.mf
! make
! include yabal.mf
! make
! include sandr.mf
! make
! include asb.mf
! make
! include anabal.mf
! make
! include avnor.mf
! make
! include apb.mf
! make
! include aprocess.mf
! make


