/* File generated by linbda Version 1.1b.0.06 : /home/Dev/abal32/src/md5/bdamd5.def -> /home/Dev/abal32/src/md5/bdamd5.c */
#ifndef __linbda__home_Dev_abal32_src_md5_bdamd5_c__
#define __linbda__home_Dev_abal32_src_md5_bdamd5_c__
#include <stdio.h>
#include <setjmp.h>
#include "ldfbda.h"

static BDA * DynamicLibrary;
	LPBDA_INIT	rt_init;
	BDA_INIT	v_rt_init;
	BDA_ARG rt_arg;

/* ABAL Runtime Error Trap */
static jmp_buf rt_error_context;
VOID rt_error(EXAWORD evalue) { 
	longjmp(rt_error_context,evalue);
	return;
}

static int function_counter=0;
/* ABAL Word Convertor */
static EXAWORD LdfAbalByte(char FAR PTR bptr)
{
	return(*bptr);
}

static EXAWORD LdfAbalWord(BYTE FAR PTR wptr)
{
	return(((*wptr<< 8) | *(wptr+1)));
}

static EXAWORD LdfAbalLong(BYTE FAR PTR wptr)
{
	return((((*wptr)<< 24) | (*(wptr+1) << 16)  | (*(wptr+2) << 8)| *(wptr+3)));
}

#define LdfParaWord(n) ( tptr[n] == 1 ? LdfAbalWord(pptr[n]) : ( tptr[n] == 0 ?  LdfAbalByte(pptr[n]) : LdfAbalLong(pptr[n])) )
#define LdfParaByte(n) ( tptr[n] == 1 ? (LdfAbalWord(pptr[n])&0x00FF) : ( tptr[n] == 0 ?  LdfAbalByte(pptr[n]) : (LdfAbalLong(pptr[n])&0x00FF) ) )
/* Library Information */
EXAWORD LdfBdaInformation(void * vptr)
{
	printf(
		"\n   Abal Dynamic Library : BdaMd532.Abal.3.1b.0.01"
		);
	printf(
		"\n   Copyright (c) 2004,2006 Amenesik / Sologic \n\n"
		);
	return(0);
}

/* Library Destructor */
EXAWORD LdfBdaTerminate()
{
	if (DynamicLibrary->fin != (VOID (FAR PTR)()) 0)
		 (*DynamicLibrary->fin)();
	return(0);
}

/* Library Call Through */
EXAWORD LdfBdaExecute(
	EXAWORD fid,
	EXAWORD argc,
	BYTE FAR tptr[],
	VOID FAR PTR FAR pptr[],
	EXAWORD FAR wptr[],
	EXAWORD FAR * eptr)
{
	EXAWORD	result=0;
	rt_arg.c=argc; rt_arg.v=pptr;
	rt_arg.l=wptr; rt_arg.t=tptr;
	if ((result=setjmp(rt_error_context))!=0) {
		if ( eptr != (EXAWORD FAR *) 0) *eptr = result;
		return( result );
		}
	/* Version = 1 */
	/* Runtime = "bdamd5" */
	switch ( fid ) {
		case	0 : /* % Md5Init() */
			result=(*DynamicLibrary->fonction[0])(); break;
		case	1 : /* % Md5File($,%,%) */
			result=(*DynamicLibrary->fonction[1])(
				pptr[0],
				LdfParaWord(1),
				LdfParaWord(2)); break;
		case	2 : /* % Md5String($,%) */
			result=(*DynamicLibrary->fonction[2])(
				pptr[0],
				LdfParaWord(1)); break;
		case	3 : /* % Md5Result($?,%) */
			result=(*DynamicLibrary->fonction[3])(
				pptr[0],
				LdfParaWord(1)); break;
		default	: result=138;
		break;
		}
	/* End */
	return(result);
}

/* Library Constructor */

EXAWORD LdfBdaInitialise(
	BDA_INIT FAR PTR descriptor,
	EXAWORD dlength)
{
	int	i=0;
	rt_init = descriptor;
	function_counter=4;
	if (!(DynamicLibrary = InitRelais()))
		return(139);
	else	return(0);
}

#endif  /* __linbda__home_Dev_abal32_src_md5_bdamd5_c__ */
/* End of File */
