! include $(ABAL)/common/host.def
! include $(ABAL)/common/agr.def
! include $(ABAL)/common/allocate.def
! include $(ABAL)/common/common.def

SRC      = $(ABAL)/src/otr/
LIB      = /lib


! include otr.mf
! make
! error thats all
! include ctr.mf
! make
! include jtr.mf
! make



