.as.at:
	otr32 -o -m -w -v $*
	ao32 -l$(@B).tc $@

p.at: p.as o.as
t.at: t.as o.as
! make

program.at: program.as iface.as
basic.at: basic.as iface.as
better.at: better.as iface.as
boom.at: boom.as iface.as
! make

