/*
 *	Projet  : ABAL			Copyright Amenesik / Sologic (c) 2003, 2012
 *	Module  : Tous
 *	Fichier : PUBEXMA.H
 *
 * Necessite PubTypes.h pour EX_FILE_HANDLE
 */

/* --------------------------------------------------------------------------
 * Mises a jour :
 * ------------
 * 06/02/12: (#BG) Ajout API SQL natif.
 */

#ifndef __PUBEXMA_H__
#define __PUBEXMA_H__

/* --------------------------------------------------------------------------
 *	Prototypes
 * --------------------------------------------------------------------------
 */


/*	Gestion */
int MA_init(void);
void MA_fin(void);
int si_ident(BYTE * , int);

WORD  EeE_IsamInfo(BYTE PTR filename,BYTE PTR pinfo);

#ifdef WIN32
/* #BG Normalement les prototypes devraient etre identiques sous WIN et UNIX ! */

/* Acces Direct */
EX_FILE_HANDLE  EeEad_create( BYTE PTR nom, WORD perm, WORD PTR perr);
WORD  EeEad_rename(EX_FILE_HANDLE hfic, BYTE PTR newname);
EX_FILE_HANDLE  EeEad_find(EX_FILE_HANDLE hfic,BYTE PTR Name,BYTE PTR pInfo);
WORD  EeEad_unlink(BYTE PTR nom);
EX_FILE_HANDLE  EeEad_open( BYTE PTR nom, WORD perm, WORD PTR perr);
WORD  EeEad_read( EX_FILE_HANDLE hfic, BYTE PTR buffer, LONG nboctets);
WORD  EeEad_write( EX_FILE_HANDLE hfic, BYTE PTR buffer, LONG nboctets);
WORD  EeEad_extend( EX_FILE_HANDLE hfic, LONG nbs);
WORD  EeEad_access( BYTE PTR nom, WORD perm);
WORD  EeEad_matb( EX_FILE_HANDLE hfic, WORD perm);
WORD  EeEad_close(EX_FILE_HANDLE hfic);
WORD  EeEad_consult( BYTE PTR nom, BYTE PTR buf1, LONG buflen1, BYTE PTR buf2, LONG buflen2);

/* Acces Sequentiel */
EX_FILE_HANDLE  EeEsq_create( BYTE PTR nom, WORD len, WORD perm, WORD PTR perr);
WORD  EeEsq_rename( EX_FILE_HANDLE hfic, BYTE PTR newname);
WORD  EeEsq_unlink(BYTE PTR nom);
EX_FILE_HANDLE  EeEsq_open(BYTE PTR nom, WORD perm, WORD PTR perr);
WORD  EeEsq_matb(EX_FILE_HANDLE hfic, WORD perm);
WORD  EeEsq_read(EX_FILE_HANDLE hfic, BYTE PTR buffer, WORD blen);
WORD  EeEsq_write(EX_FILE_HANDLE hfic, BYTE PTR buffer, WORD blen);
WORD  EeEsq_modif(EX_FILE_HANDLE hfic, BYTE PTR buffer, WORD blen);
WORD  EeEsq_rewind(EX_FILE_HANDLE hfic);
WORD  EeEsq_close(EX_FILE_HANDLE hfic);

/* Acces Sequentiel Indexe */
EX_FILE_HANDLE  EeEsi_create(BYTE PTR, WORD, WORD, WORD, WORD, WORD, WORD PTR);
WORD  EeEsi_rename(EX_FILE_HANDLE, BYTE PTR);
WORD  EeEsi_unlink(BYTE PTR);
EX_FILE_HANDLE  EeEsi_open(BYTE PTR, WORD, WORD PTR);
WORD  EeEsi_matb(EX_FILE_HANDLE, WORD);
WORD  EeEsi_close(EX_FILE_HANDLE);
WORD  EeEsi_writezc(EX_FILE_HANDLE, BYTE PTR, WORD);
WORD  EeEsi_readzc(EX_FILE_HANDLE, WORD, BYTE PTR, WORD);
WORD  EeEsi_insert(EX_FILE_HANDLE, BYTE PTR, BYTE, BYTE PTR, WORD);
WORD  EeEsi_delete(EX_FILE_HANDLE, BYTE PTR, BYTE);
WORD  EeEsi_modif(EX_FILE_HANDLE, BYTE PTR, BYTE, BYTE PTR, WORD);
WORD  EeEsi_search(EX_FILE_HANDLE, WORD, WORD, BYTE PTR, BYTE, BYTE PTR, WORD);
WORD  EeEsi_down(EX_FILE_HANDLE, WORD, WORD, BYTE, BYTE PTR, WORD);
WORD  EeEsi_up(EX_FILE_HANDLE, WORD, WORD, BYTE, BYTE PTR, WORD);
WORD  EeEsi_criext(EX_FILE_HANDLE, BYTE PTR, WORD, BYTE PTR, WORD);

/* Acces Multicriteres */
EX_FILE_HANDLE  EeEmc_create(BYTE PTR, WORD, WORD, WORD, WORD, WORD, WORD PTR);
WORD  EeEmc_rename(EX_FILE_HANDLE, BYTE PTR);
WORD  EeEmc_unlink(BYTE PTR);
EX_FILE_HANDLE  EeEmc_open(BYTE PTR, WORD, WORD PTR);
WORD  EeEmc_matb(EX_FILE_HANDLE, WORD);
WORD  EeEmc_close(EX_FILE_HANDLE);
WORD  EeEmc_insert(EX_FILE_HANDLE, BYTE PTR, BYTE, BYTE PTR, WORD);
WORD  EeEmc_delete(EX_FILE_HANDLE, BYTE PTR, BYTE);
WORD  EeEmc_modif(EX_FILE_HANDLE, BYTE PTR, BYTE, BYTE PTR, WORD);
WORD  EeEmc_search(EX_FILE_HANDLE, WORD, WORD, BYTE PTR, BYTE, BYTE PTR, WORD);
WORD  EeEmc_down(EX_FILE_HANDLE, WORD, WORD, BYTE, BYTE PTR, WORD);
WORD  EeEmc_up(EX_FILE_HANDLE, WORD, WORD, BYTE, BYTE PTR, WORD);
WORD  EeEmc_ckey(EX_FILE_HANDLE, BYTE PTR, WORD, WORD);
WORD  EeEmc_nkey(EX_FILE_HANDLE, BYTE PTR, BYTE PTR);
WORD  EeEmc_fkey(EX_FILE_HANDLE, BYTE PTR, BYTE PTR, WORD, WORD, WORD);
WORD  EeEmc_updndx(EX_FILE_HANDLE);
WORD  EeEmc_cndx(EX_FILE_HANDLE, BYTE PTR, WORD);
WORD  EeEmc_dndx(EX_FILE_HANDLE, BYTE PTR, WORD);
WORD  EeEmc_dcndx(EX_FILE_HANDLE, BYTE PTR, WORD);
WORD  EeEmc_ddndx(EX_FILE_HANDLE, BYTE PTR, WORD);
WORD  EeEmc_lkey(EX_FILE_HANDLE, BYTE PTR, WORD, WORD);
WORD  EeEmc_lndx(EX_FILE_HANDLE, BYTE PTR, WORD, WORD);
WORD  EeEmc_info(EX_FILE_HANDLE, BYTE PTR, WORD);
WORD  EeEmc_count(EX_FILE_HANDLE, BYTE PTR, WORD, WORD, WORD, LONG PTR);
WORD  EeEmc_posit(EX_FILE_HANDLE, BYTE PTR, WORD, WORD, WORD, WORD, WORD PTR);
WORD  EeEmc_collect(EX_FILE_HANDLE, BYTE PTR, WORD, WORD, WORD, WORD, WORD, WORD PTR, BYTE PTR, WORD PTR, LONG PTR);

/* Acces Base de Donnees */
EX_FILE_HANDLE  EeEbd_create(BYTE PTR, WORD, WORD PTR);
WORD  EeEbd_rename(EX_FILE_HANDLE, BYTE PTR);
WORD  EeEbd_unlink(BYTE PTR);
EX_FILE_HANDLE  EeEbd_open(BYTE PTR, WORD, WORD PTR);
WORD  EeEbd_matb(EX_FILE_HANDLE, WORD);
WORD  EeEbd_close(EX_FILE_HANDLE);
EX_FILE_HANDLE  EeEbf_create(BYTE PTR, WORD, WORD, WORD, WORD, WORD, EX_FILE_HANDLE, WORD PTR);
WORD  EeEbf_rename(EX_FILE_HANDLE, BYTE PTR);
WORD  EeEbf_unlink(BYTE PTR, EX_FILE_HANDLE, WORD);
EX_FILE_HANDLE  EeEbf_open(BYTE PTR, WORD, EX_FILE_HANDLE, WORD PTR);
WORD  EeEbf_close(EX_FILE_HANDLE);
WORD  EeEbf_insert(EX_FILE_HANDLE, BYTE PTR, BYTE, BYTE PTR, WORD);
WORD  EeEbf_delete(EX_FILE_HANDLE, BYTE PTR, BYTE);
WORD  EeEbf_modif(EX_FILE_HANDLE, BYTE PTR, BYTE, BYTE PTR, WORD);
WORD  EeEbf_search(EX_FILE_HANDLE, WORD, WORD, BYTE PTR, BYTE, BYTE PTR, WORD);
WORD  EeEbf_down(EX_FILE_HANDLE, WORD, WORD, BYTE, BYTE PTR, WORD);
WORD  EeEbf_up(EX_FILE_HANDLE, WORD, WORD, BYTE, BYTE PTR, WORD);
WORD  EeEbd_ckey(EX_FILE_HANDLE, BYTE PTR, WORD, WORD);
WORD  EeEbd_nkey(EX_FILE_HANDLE, BYTE PTR, BYTE PTR);
WORD  EeEbd_fkey(EX_FILE_HANDLE, BYTE PTR, BYTE PTR, WORD, WORD, WORD);
WORD  EeEbd_updndx(EX_FILE_HANDLE);
WORD  EeEbd_cndx(EX_FILE_HANDLE, BYTE PTR, WORD);
WORD  EeEbd_dndx(EX_FILE_HANDLE, BYTE PTR, WORD);
WORD  EeEbd_dcndx(EX_FILE_HANDLE, BYTE PTR, WORD);
WORD  EeEbd_ddndx(EX_FILE_HANDLE, BYTE PTR, WORD);
WORD  EeEbd_join(EX_FILE_HANDLE, BYTE PTR, WORD);
WORD  EeEbd_cjoin(EX_FILE_HANDLE, BYTE PTR, WORD, WORD);
WORD  EeEbd_djoin(EX_FILE_HANDLE, BYTE PTR);
WORD  EeEbd_rjoin(EX_FILE_HANDLE, BYTE PTR, WORD);
WORD  EeEbd_info(EX_FILE_HANDLE, BYTE PTR, WORD);
WORD  EeEbf_info(EX_FILE_HANDLE, BYTE PTR, WORD);
WORD  EeEbd_lfile(EX_FILE_HANDLE, BYTE PTR, WORD, WORD);
WORD  EeEbd_ljoin(EX_FILE_HANDLE, BYTE PTR, WORD, WORD);
WORD  EeEbd_lkey(EX_FILE_HANDLE, BYTE PTR, WORD, WORD);
WORD  EeEbd_llink(EX_FILE_HANDLE, BYTE PTR, WORD, WORD);
WORD  EeEbd_count(EX_FILE_HANDLE, BYTE PTR, WORD, WORD, WORD, LONG PTR);
WORD  EeEbd_posit(EX_FILE_HANDLE, BYTE PTR, WORD, WORD, WORD, WORD, WORD PTR);
WORD  EeEbd_updown(EX_FILE_HANDLE, WORD, WORD, WORD PTR, BYTE PTR, WORD);

#else /* WIN32 */

//#include "exadsqcr.h"

/* Acces Direct */
EX_FILE_HANDLE EeEad_create(BPTR, EXAWORD, WPTR);
EXAWORD EeEad_rename(EX_FILE_HANDLE, BPTR);
EXAWORD EeEad_find(EX_FILE_HANDLE, BPTR, BPTR);
EXAWORD EeEad_unlink(BPTR);
EX_FILE_HANDLE EeEad_open(BPTR, EXAWORD, WPTR);
EXAWORD EeEad_read(EX_FILE_HANDLE, BPTR, EXAWORD);
EXAWORD EeEad_write(EX_FILE_HANDLE, BPTR, EXAWORD);
EXAWORD EeEad_extend(EX_FILE_HANDLE, EXAWORD);
EXAWORD EeEad_access(BPTR, EXAWORD);
EXAWORD EeEad_matb(EX_FILE_HANDLE, EXAWORD);
EXAWORD EeEad_close(EX_FILE_HANDLE);

/* Acces Sequentiel */
EX_FILE_HANDLE EeEsq_create(BPTR, EXAWORD, EXAWORD, WPTR);
EXAWORD EeEsq_rename(EX_FILE_HANDLE, BPTR);
EXAWORD EeEsq_unlink(BPTR);
EX_FILE_HANDLE EeEsq_open(BPTR, EXAWORD, WPTR);
EXAWORD EeEsq_matb(EX_FILE_HANDLE, EXAWORD);
EXAWORD EeEsq_read(EX_FILE_HANDLE, BPTR, EXAWORD);
EXAWORD EeEsq_write(EX_FILE_HANDLE, BPTR, EXAWORD);
EXAWORD EeEsq_modif(EX_FILE_HANDLE, BPTR, EXAWORD);
EXAWORD EeEsq_rewind(EX_FILE_HANDLE);
EXAWORD EeEsq_close(EX_FILE_HANDLE);

/* Acces Sequentiel Indexe */
EX_FILE_HANDLE EeEsi_create(BPTR, EXAWORD, EXAWORD, EXAWORD, EXAWORD, EXAWORD, WPTR);
EXAWORD EeEsi_rename(EX_FILE_HANDLE, BPTR);
EXAWORD EeEsi_unlink(BPTR);
EX_FILE_HANDLE EeEsi_open(BPTR, EXAWORD, WPTR);
EXAWORD EeEsi_matb(EX_FILE_HANDLE, EXAWORD);
EXAWORD EeEsi_close(EX_FILE_HANDLE);
EXAWORD EeEsi_writezc(EX_FILE_HANDLE, BPTR, EXAWORD);
EXAWORD EeEsi_readzc(EX_FILE_HANDLE, EXAWORD, BPTR, EXAWORD);
EXAWORD EeEsi_insert(EX_FILE_HANDLE, BPTR, EXABYTE, BPTR, EXAWORD);
EXAWORD EeEsi_delete(EX_FILE_HANDLE, BPTR, EXABYTE);
EXAWORD EeEsi_modif(EX_FILE_HANDLE, BPTR, EXABYTE, BPTR, EXAWORD);
EXAWORD EeEsi_search(EX_FILE_HANDLE, EXAWORD, EXAWORD, BPTR, EXABYTE, BPTR, EXAWORD);
EXAWORD EeEsi_down(EX_FILE_HANDLE, EXAWORD, EXAWORD, EXABYTE, BPTR, EXAWORD);
EXAWORD EeEsi_up(EX_FILE_HANDLE, EXAWORD, EXAWORD, EXABYTE, BPTR, EXAWORD);
EXAWORD EeEsi_criext(EX_FILE_HANDLE, BPTR, EXAWORD, BPTR, EXAWORD);

/* Acces Multicriteres */
EX_FILE_HANDLE EeEmc_create(BPTR, EXAWORD, EXAWORD, EXAWORD, EXAWORD, EXAWORD, WPTR);
EXAWORD EeEmc_rename(EX_FILE_HANDLE, BPTR);
EXAWORD EeEmc_unlink(BPTR);
EX_FILE_HANDLE EeEmc_open(BPTR, EXAWORD, WPTR);
EXAWORD EeEmc_matb(EX_FILE_HANDLE, EXAWORD);
EXAWORD EeEmc_close(EX_FILE_HANDLE);
EXAWORD EeEmc_insert(EX_FILE_HANDLE, BPTR, EXABYTE, BPTR, EXAWORD);
EXAWORD EeEmc_delete(EX_FILE_HANDLE, BPTR, EXABYTE);
EXAWORD EeEmc_modif(EX_FILE_HANDLE, BPTR, EXABYTE, BPTR, EXAWORD);
EXAWORD EeEmc_search(EX_FILE_HANDLE, EXAWORD, EXAWORD, BPTR, EXABYTE, BPTR, EXAWORD);
EXAWORD EeEmc_down(EX_FILE_HANDLE, EXAWORD, EXAWORD, EXABYTE, BPTR, EXAWORD);
EXAWORD EeEmc_up(EX_FILE_HANDLE, EXAWORD, EXAWORD, EXABYTE, BPTR, EXAWORD);
EXAWORD EeEmc_ckey(EX_FILE_HANDLE, BPTR, EXAWORD, EXAWORD);
EXAWORD EeEmc_nkey(EX_FILE_HANDLE, BPTR, BPTR);
EXAWORD EeEmc_fkey(EX_FILE_HANDLE, BPTR, BPTR, EXAWORD, EXAWORD, EXAWORD);
EXAWORD EeEmc_updndx(EX_FILE_HANDLE);
EXAWORD EeEmc_cndx(EX_FILE_HANDLE, BPTR, EXAWORD);
EXAWORD EeEmc_dndx(EX_FILE_HANDLE, BPTR, EXAWORD);
EXAWORD EeEmc_dcndx(EX_FILE_HANDLE, BPTR, EXAWORD);
EXAWORD EeEmc_ddndx(EX_FILE_HANDLE, BPTR, EXAWORD);
EXAWORD EeEmc_lkey(EX_FILE_HANDLE, BPTR, EXAWORD, EXAWORD);
EXAWORD EeEmc_lndx(EX_FILE_HANDLE, BPTR, EXAWORD, EXAWORD);
EXAWORD EeEmc_info(EX_FILE_HANDLE, BPTR, EXAWORD);
EXAWORD EeEmc_count(EX_FILE_HANDLE, BPTR, EXAWORD, EXAWORD, EXAWORD, EXALONG PTR);
EXAWORD EeEmc_posit(EX_FILE_HANDLE, BPTR, EXAWORD, EXAWORD, EXAWORD, EXAWORD, WPTR);

/* Acces Base de Donnees */
EX_FILE_HANDLE EeEbd_create(BPTR, EXAWORD, WPTR);
EXAWORD EeEbd_rename(EX_FILE_HANDLE, BPTR);
EXAWORD EeEbd_unlink(BPTR);
EX_FILE_HANDLE EeEbd_open(BPTR, EXAWORD, WPTR);
EXAWORD EeEbd_matb(EX_FILE_HANDLE, EXAWORD);
EXAWORD EeEbd_close(EX_FILE_HANDLE);
EX_FILE_HANDLE EeEbf_create(BPTR, EXAWORD, EXAWORD, EXAWORD, EXAWORD, EXAWORD, EX_FILE_HANDLE, WPTR);
EXAWORD EeEbf_rename(EX_FILE_HANDLE, BPTR);
EXAWORD EeEbf_unlink(BPTR, EX_FILE_HANDLE, EXAWORD);
EX_FILE_HANDLE EeEbf_open(BPTR, EXAWORD, EX_FILE_HANDLE, WPTR);
EXAWORD EeEbf_close(EX_FILE_HANDLE);
EXAWORD EeEbf_insert(EX_FILE_HANDLE, BPTR, EXABYTE, BPTR, EXAWORD);
EXAWORD EeEbf_delete(EX_FILE_HANDLE, BPTR, EXABYTE);
EXAWORD EeEbf_modif(EX_FILE_HANDLE, BPTR, EXABYTE, BPTR, EXAWORD);
EXAWORD EeEbf_search(EX_FILE_HANDLE, EXAWORD, EXAWORD, BPTR, EXABYTE, BPTR, EXAWORD);
EXAWORD EeEbf_down(EX_FILE_HANDLE, EXAWORD, EXAWORD, EXABYTE, BPTR, EXAWORD);
EXAWORD EeEbf_up(EX_FILE_HANDLE, EXAWORD, EXAWORD, EXABYTE, BPTR, EXAWORD);
EXAWORD EeEbd_ckey(EX_FILE_HANDLE, BPTR, EXAWORD, EXAWORD);
EXAWORD EeEbd_nkey(EX_FILE_HANDLE, BPTR, BPTR);
EXAWORD EeEbd_fkey(EX_FILE_HANDLE, BPTR, BPTR, EXAWORD, EXAWORD, EXAWORD);
EXAWORD EeEbd_updndx(EX_FILE_HANDLE);
EXAWORD EeEbd_cndx(EX_FILE_HANDLE, BPTR, EXAWORD);
EXAWORD EeEbd_dndx(EX_FILE_HANDLE, BPTR, EXAWORD);
EXAWORD EeEbd_dcndx(EX_FILE_HANDLE, BPTR, EXAWORD);
EXAWORD EeEbd_ddndx(EX_FILE_HANDLE, BPTR, EXAWORD);
EXAWORD EeEbd_join(EX_FILE_HANDLE, BPTR, EXAWORD);
EXAWORD EeEbd_cjoin(EX_FILE_HANDLE, BPTR, EXAWORD, EXAWORD);
EXAWORD EeEbd_djoin(EX_FILE_HANDLE, BPTR);
EXAWORD EeEbd_rjoin(EX_FILE_HANDLE, BPTR, EXAWORD);
EXAWORD EeEbd_info(EX_FILE_HANDLE, BPTR, EXAWORD);
EXAWORD EeEbf_info(EX_FILE_HANDLE, BPTR, EXAWORD);
EXAWORD EeEbd_lfile(EX_FILE_HANDLE, BPTR, EXAWORD, EXAWORD);
EXAWORD EeEbd_ljoin(EX_FILE_HANDLE, BPTR, EXAWORD, EXAWORD);
EXAWORD EeEbd_lkey(EX_FILE_HANDLE, BPTR, EXAWORD, EXAWORD);
EXAWORD EeEbd_llink(EX_FILE_HANDLE, BPTR, EXAWORD, EXAWORD);
EXAWORD EeEbd_count(EX_FILE_HANDLE, BPTR, EXAWORD, EXAWORD, EXAWORD, EXALONG PTR);
EXAWORD EeEbd_posit(EX_FILE_HANDLE, BPTR, EXAWORD, EXAWORD, EXAWORD, EXAWORD, WPTR);
EXAWORD EeEbd_updown(EX_FILE_HANDLE, EXAWORD, EXAWORD, WPTR, BPTR, EXAWORD);

#endif  /* WIN32 */

#ifdef ABALSQL
/*	Acces SQL */
int MASQL_connect(BYTE PTR ConnInfos, int LgConnInfos, EX_FILE_HANDLE* pHdleConn);
int MASQL_disconnect(EX_FILE_HANDLE HdleConn);
int MASQL_getSqlErrorMessage(EX_FILE_HANDLE HdleConn, BYTE PTR ErrorMsg, int LgErrorMsg);
int MASQL_getInfosVersion(EX_FILE_HANDLE HdleConn, int TypeInfos, BYTE PTR Infos, int LgInfos);
int MASQL_bindParam(EX_FILE_HANDLE HdleConn, EX_FILE_HANDLE HdleStmt, int NumParam, BYTE PTR AdrParam, int TypeParam, int LengthParam, int LgDec, BYTE PTR AdrExt, int TypeExt, int LengthExt);
int MASQL_clear(EX_FILE_HANDLE HdleConn, EX_FILE_HANDLE HdleStmt);
int MASQL_exec(EX_FILE_HANDLE HdleConn, BYTE PTR Query, int LgQuery, int FormatRes, EX_FILE_HANDLE* pHdleStmt);
int MASQL_execPrepared(EX_FILE_HANDLE HdleConn, EX_FILE_HANDLE HdleStmt, int FormatRes);
int MASQL_prepare(EX_FILE_HANDLE HdleConn, BYTE PTR QryName, int LgName, BYTE PTR Query, int LgQuery, int NbParams, int FormatRes, EX_FILE_HANDLE* pHdleStmt);
int MASQL_bindCol(EX_FILE_HANDLE HdleConn, EX_FILE_HANDLE HdleStmt, int NumCol, BYTE PTR AdrCol, int TypeCol, int LengthCol, int LgDec, BYTE PTR AdrExt, int TypeExt, int LengthExt);
int MASQL_fetchRow(EX_FILE_HANDLE HdleConn, EX_FILE_HANDLE HdleStmt, int Sens);
int MASQL_fetchRowNum(EX_FILE_HANDLE HdleConn, EX_FILE_HANDLE HdleStmt, int NumRow);
int MASQL_getStmtColName(EX_FILE_HANDLE HdleConn, EX_FILE_HANDLE HdleStmt, int NumCol, BYTE PTR ColName, int LgColName);
int MASQL_getStmtColumns(EX_FILE_HANDLE HdleConn, EX_FILE_HANDLE HdleStmt, int* pNbColumns);
int MASQL_getStmtRows(EX_FILE_HANDLE HdleConn, EX_FILE_HANDLE HdleStmt, int* pNbRow);
int MASQL_getValue(EX_FILE_HANDLE HdleConn, EX_FILE_HANDLE HdleStmt, int NumRow, int NumCol, BYTE PTR AdrCol, int TypeCol, int LengthCol, int LgDec, BYTE PTR AdrExt, int TypeExt, int LengthExt);
int MASQL_beginTrans(EX_FILE_HANDLE HdleConn, int Level);
int MASQL_commitTrans(EX_FILE_HANDLE HdleConn);
int MASQL_rollbackTrans(EX_FILE_HANDLE HdleConn);
#endif

#endif //__PUBEXMA_H__
