/* File generated by /home/abal64/bin/linbda Version 2.1a.0.03 : /home/abal64/src/zgr/z.def -> /home/abal64/src/zgr/z.c */
#ifndef __linbda__home_abal64_src_zgr_z_c__
#define __linbda__home_abal64_src_zgr_z_c__
#include <stdio.h>
#include <setjmp.h>
#include "ldfbda.h"

private BDA * DynamicLibrary;
	public  LPBDA_INIT	rt_init;
	public  BDA_INIT	v_rt_init;
	public  BDA_ARG rt_arg;

/* ABAL Runtime Error Trap */
private	jmp_buf rt_error_context;
public  VOID rt_error(EXAWORD evalue) { 
	longjmp(rt_error_context,evalue);
	return;
}

private int function_counter=0;
/* ABAL Word Conversions */
public EXAWORD GetAbalInt8(char FAR PTR bptr)
{
	return(*bptr);
}

public EXAWORD GetAbalInt16(BYTE FAR PTR wptr)
{
	return(((*wptr<< 8)|*(wptr+1)));
}

public EXAWORD GetAbalInt32(BYTE FAR PTR wptr)
{
	int length=4;
	EXAWORD result=0;
	while ( length-- ) result = ((result << 8) | (*(wptr++) & 0x00FF));
	return(result);
}

public EXAWORD GetAbalInt64(BYTE FAR PTR wptr)
{
	int length=8;
	EXAWORD result=0;
	while ( length-- ) result = ((result << 8) | (*(wptr++) & 0x00FF));
	return(result);
}

public void PutAbalInt8(char FAR * wptr, EXAWORD v)
{
	*wptr = (v & 0x00FF);
	return;
}
public void PutAbalInt16(BYTE FAR * wptr, EXAWORD v)
{
	int length=2;
	while ( length-- ) { *(wptr +length) = (v & 0x00FF); v >>= 8; }
	return;
}

public void PutAbalInt32(BYTE FAR * wptr, EXAWORD v)
{
	int length=4;
	while ( length-- ) { *(wptr +length) = (v & 0x00FF); v >>= 8; }
	return;
}

public void PutAbalInt64(BYTE FAR * wptr, EXAWORD v)
{
	int length=8;
	while ( length-- ) { *(wptr +length) = (v & 0x00FF); v >>= 8; }
	return;
}

#define LdfParaWord(n) (tptr[n]==1 ? GetAbalInt16(pptr[n]) : (tptr[n]==0 ? GetAbalInt8(pptr[n]) : (tptr[n]==5 ? GetAbalInt32(pptr[n]): GetAbalInt64(pptr[n]) )))
#define LdfParaByte(n) (tptr[n]==1 ? (GetAbalInt16(pptr[n])&0x00FF) : (tptr[n]==0 ? GetAbalInt8(pptr[n]):(tptr[n]==5?(GetAbalInt32(pptr[n])&0x00FF):(GetAbalInt64(pptr[n])&0x00FF))))
/* Library Information */
public EXAWORD LdfBdaInformation(void * vptr)
{
	printf(
		"\n   Abal Dynamic Library : ZGR64.Abal.3.3u.0.01"
		);
	printf(
		"\n   Copyright (c) Amenesik / Sologic \n\n"
		);
	return(0);
}

/* Library Destructor */
public EXAWORD LdfBdaTerminate()
{
	if (DynamicLibrary->fin != (VOID (FAR PTR)()) 0)
		 (*DynamicLibrary->fin)();
	return(0);
}

/* Library Call Through */
public EXAWORD LdfBdaExecute(
	EXAWORD fid,
	EXAWORD argc,
	BYTE FAR tptr[],
	VOID FAR PTR FAR pptr[],
	EXAWORD FAR wptr[],
	int FAR * eptr)
{
	EXAWORD	result=0;
	rt_arg.c=argc; rt_arg.v=pptr;
	rt_arg.l=wptr; rt_arg.t=tptr;
	if ((result=setjmp(rt_error_context))!=0) {
		if ( eptr != (int FAR *) 0) *eptr = result;
		return( result );
		}
	/* version = 1 */
	/* runtime = "z" */
	switch ( fid ) {
		case	0 : /* %zzinit($) */
			result=(*DynamicLibrary->fonction[0])(
				pptr[0]); break;
		case	1 : /* %zzinitmouse($) */
			result=(*DynamicLibrary->fonction[1])(
				pptr[0]); break;
		case	2 : /* zzshowmouse() */
			result=(*DynamicLibrary->fonction[2])(); break;
		case	3 : /* zzhidemouse() */
			result=(*DynamicLibrary->fonction[3])(); break;
		case	4 : /* zzreserve1() */
			result=(*DynamicLibrary->fonction[4])(); break;
		case	5 : /* zzstatusmouse($) */
			result=(*DynamicLibrary->fonction[5])(
				pptr[0]); break;
		case	6 : /* zzreserve2() */
			result=(*DynamicLibrary->fonction[6])(); break;
		case	7 : /* zzreserve3() */
			result=(*DynamicLibrary->fonction[7])(); break;
		case	8 : /* %zrlecpt($,$,%) */
			result=(*DynamicLibrary->fonction[8])(
				pptr[0],
				pptr[1],
				LdfParaWord(2)); break;
		case	9 : /* %zrledcpt($,$,%) */
			result=(*DynamicLibrary->fonction[9])(
				pptr[0],
				pptr[1],
				LdfParaWord(2)); break;
		case	10 : /* zzreserve4() */
			result=(*DynamicLibrary->fonction[10])(); break;
		case	11 : /* zzreserve5() */
			result=(*DynamicLibrary->fonction[11])(); break;
		case	12 : /* zzreserve6() */
			result=(*DynamicLibrary->fonction[12])(); break;
		case	13 : /* zzreserve7() */
			result=(*DynamicLibrary->fonction[13])(); break;
		case	14 : /* zbprint(%,$,%,%) */
			result=(*DynamicLibrary->fonction[14])(
				LdfParaWord(0),
				pptr[1],
				LdfParaWord(2),
				LdfParaWord(3)); break;
		case	15 : /* zbprintxy(%,%,%,$) */
			result=(*DynamicLibrary->fonction[15])(
				LdfParaWord(0),
				LdfParaWord(1),
				LdfParaWord(2),
				pptr[3]); break;
		case	16 : /* zbhide(%) */
			result=(*DynamicLibrary->fonction[16])(
				LdfParaWord(0)); break;
		case	17 : /* zbshow(%,%,%,%,%) */
			result=(*DynamicLibrary->fonction[17])(
				LdfParaWord(0),
				LdfParaWord(1),
				LdfParaWord(2),
				LdfParaWord(3),
				LdfParaWord(4)); break;
		case	18 : /* zzwait1_10() */
			result=(*DynamicLibrary->fonction[18])(); break;
		case	19 : /* %zwanal($,%,%,%?,%?,%?,%?,%?) */
			result=(*DynamicLibrary->fonction[19])(
				pptr[0],
				LdfParaWord(1),
				LdfParaWord(2),
				pptr[3],
				pptr[4],
				pptr[5],
				pptr[6],
				pptr[7]); break;
		case	20 : /* zzend() */
			result=(*DynamicLibrary->fonction[20])(); break;
		case	21 : /* zz_adrs($) */
			result=(*DynamicLibrary->fonction[21])(
				pptr[0]); break;
		case	22 : /* %zzpush(%,%,%,%,%) */
			result=(*DynamicLibrary->fonction[22])(
				LdfParaWord(0),
				LdfParaWord(1),
				LdfParaWord(2),
				LdfParaWord(3),
				LdfParaWord(4)); break;
		case	23 : /* %zzpop() */
			result=(*DynamicLibrary->fonction[23])(); break;
		case	24 : /* %zzwmove(%,%) */
			result=(*DynamicLibrary->fonction[24])(
				LdfParaWord(0),
				LdfParaWord(1)); break;
		case	25 : /* zzshadow(%,%,%,%)  */
			result=(*DynamicLibrary->fonction[25])(
				LdfParaWord(0),
				LdfParaWord(1),
				LdfParaWord(2),
				LdfParaWord(3)); break;
		case	26 : /* %zscroll(%,%,%,%,%,%) */
			result=(*DynamicLibrary->fonction[26])(
				LdfParaWord(0),
				LdfParaWord(1),
				LdfParaWord(2),
				LdfParaWord(3),
				LdfParaWord(4),
				LdfParaWord(5)); break;
		case	27 : /* azac_init(%) */
			result=(*DynamicLibrary->fonction[27])(
				LdfParaWord(0)); break;
		case	28 : /* %azac_open(%,$,%) */
			result=(*DynamicLibrary->fonction[28])(
				LdfParaWord(0),
				pptr[1],
				LdfParaWord(2)); break;
		case	29 : /* %azac_nextline(%,$,%?) */
			result=(*DynamicLibrary->fonction[29])(
				LdfParaWord(0),
				pptr[1],
				pptr[2]); break;
		case	30 : /* %azac_prevline(%,$,%?) */
			result=(*DynamicLibrary->fonction[30])(
				LdfParaWord(0),
				pptr[1],
				pptr[2]); break;
		case	31 : /* %azac_firstline(%,$,%?) */
			result=(*DynamicLibrary->fonction[31])(
				LdfParaWord(0),
				pptr[1],
				pptr[2]); break;
		case	32 : /* %azac_lastline(%,$,%?) */
			result=(*DynamicLibrary->fonction[32])(
				LdfParaWord(0),
				pptr[1],
				pptr[2]); break;
		case	33 : /* azac_close(%) */
			result=(*DynamicLibrary->fonction[33])(
				LdfParaWord(0)); break;
		case	34 : /* %azac_create(%,$) */
			result=(*DynamicLibrary->fonction[34])(
				LdfParaWord(0),
				pptr[1]); break;
		case	35 : /* %azac_write(%,$,%) */
			result=(*DynamicLibrary->fonction[35])(
				LdfParaWord(0),
				pptr[1],
				LdfParaWord(2)); break;
		case	36 : /* zbprintvar(%,%,%,$) */
			result=(*DynamicLibrary->fonction[36])(
				LdfParaWord(0),
				LdfParaWord(1),
				LdfParaWord(2),
				pptr[3]); break;
		case	37 : /* zbprintitem(%,%,%,$,$,%,%,%) */
			result=(*DynamicLibrary->fonction[37])(
				LdfParaWord(0),
				LdfParaWord(1),
				LdfParaWord(2),
				pptr[3],
				pptr[4],
				LdfParaWord(5),
				LdfParaWord(6),
				LdfParaWord(7)); break;
		case	38 : /* zprintran(%,$) */
			result=(*DynamicLibrary->fonction[38])(
				LdfParaWord(0),
				pptr[1]); break;
		case	39 : /* %ztab_2_seq(%,%,$,$,$,%,%,$,$,%) */
			result=(*DynamicLibrary->fonction[39])(
				LdfParaWord(0),
				LdfParaWord(1),
				pptr[2],
				pptr[3],
				pptr[4],
				LdfParaWord(5),
				LdfParaWord(6),
				pptr[7],
				pptr[8],
				LdfParaWord(9)); break;
		case	40 : /* %zstring_cpt($,%,$) */
			result=(*DynamicLibrary->fonction[40])(
				pptr[0],
				LdfParaWord(1),
				pptr[2]); break;
		case	41 : /* %zzfind($,$,%,%) */
			result=(*DynamicLibrary->fonction[41])(
				pptr[0],
				pptr[1],
				LdfParaWord(2),
				LdfParaWord(3)); break;
		case	42 : /* %azac_read(%,$,%) */
			result=(*DynamicLibrary->fonction[42])(
				LdfParaWord(0),
				pptr[1],
				LdfParaWord(2)); break;
		case	43 : /* %zindex($,#,%,%) */
			result=(*DynamicLibrary->fonction[43])(
				pptr[0],
				LdfParaByte(1),
				LdfParaWord(2),
				LdfParaWord(3)); break;
		case	44 : /* zoem2ansi($,%) */
			result=(*DynamicLibrary->fonction[44])(
				pptr[0],
				LdfParaWord(1)); break;
		case	45 : /* zansi2oem($,%) */
			result=(*DynamicLibrary->fonction[45])(
				pptr[0],
				LdfParaWord(1)); break;
		case	46 : /* %zwinhelp($,%,$?) */
			result=(*DynamicLibrary->fonction[46])(
				pptr[0],
				LdfParaWord(1),
				pptr[2]); break;
		case	47 : /* zzreserve16() */
			result=(*DynamicLibrary->fonction[47])(); break;
		case	48 : /* zzreserve17() */
			result=(*DynamicLibrary->fonction[48])(); break;
		case	49 : /* zzreserve18() */
			result=(*DynamicLibrary->fonction[49])(); break;
		case	50 : /* zwin_mesval($,%) */
			result=(*DynamicLibrary->fonction[50])(
				pptr[0],
				LdfParaWord(1)); break;
		case	51 : /* zwin_messerr($,%) */
			result=(*DynamicLibrary->fonction[51])(
				pptr[0],
				LdfParaWord(1)); break;
		case	52 : /* %zwin_mesyesno($,%,%) */
			result=(*DynamicLibrary->fonction[52])(
				pptr[0],
				LdfParaWord(1),
				LdfParaWord(2)); break;
		case	53 : /* %zwin_mesync($,%) */
			result=(*DynamicLibrary->fonction[53])(
				pptr[0],
				LdfParaWord(1)); break;
		case	54 : /* zwin_button(%,%,%,%,%,$,%,$) */
			result=(*DynamicLibrary->fonction[54])(
				LdfParaWord(0),
				LdfParaWord(1),
				LdfParaWord(2),
				LdfParaWord(3),
				LdfParaWord(4),
				pptr[5],
				LdfParaWord(6),
				pptr[7]); break;
		case	55 : /* zwin_smallbutton(%,%,%,%,$,%,$) */
			result=(*DynamicLibrary->fonction[55])(
				LdfParaWord(0),
				LdfParaWord(1),
				LdfParaWord(2),
				LdfParaWord(3),
				pptr[4],
				LdfParaWord(5),
				pptr[6]); break;
		case	56 : /* zwin_F1button(%,%,%) */
			result=(*DynamicLibrary->fonction[56])(
				LdfParaWord(0),
				LdfParaWord(1),
				LdfParaWord(2)); break;
		case	57 : /* %zwin_vlift(%,%,%,%,%,%,%) */
			result=(*DynamicLibrary->fonction[57])(
				LdfParaWord(0),
				LdfParaWord(1),
				LdfParaWord(2),
				LdfParaWord(3),
				LdfParaWord(4),
				LdfParaWord(5),
				LdfParaWord(6)); break;
		case	58 : /* zwin_lisf_lift(%,%,%,%,%) */
			result=(*DynamicLibrary->fonction[58])(
				LdfParaWord(0),
				LdfParaWord(1),
				LdfParaWord(2),
				LdfParaWord(3),
				LdfParaWord(4)); break;
		case	59 : /* zwin_frame(%,%,%,%,%,%,%,%,$) */
			result=(*DynamicLibrary->fonction[59])(
				LdfParaWord(0),
				LdfParaWord(1),
				LdfParaWord(2),
				LdfParaWord(3),
				LdfParaWord(4),
				LdfParaWord(5),
				LdfParaWord(6),
				LdfParaWord(7),
				pptr[8]); break;
		case	60 : /* zwin_window(%,%,%,%,%,%,%,$,%,%) */
			result=(*DynamicLibrary->fonction[60])(
				LdfParaWord(0),
				LdfParaWord(1),
				LdfParaWord(2),
				LdfParaWord(3),
				LdfParaWord(4),
				LdfParaWord(5),
				LdfParaWord(6),
				pptr[7],
				LdfParaWord(8),
				LdfParaWord(9)); break;
		case	61 : /* %zwin_font(%) */
			result=(*DynamicLibrary->fonction[61])(
				LdfParaWord(0)); break;
		case	62 : /* zwin_check(%,%,%,%,%,%) */
			result=(*DynamicLibrary->fonction[62])(
				LdfParaWord(0),
				LdfParaWord(1),
				LdfParaWord(2),
				LdfParaWord(3),
				LdfParaWord(4),
				LdfParaWord(5)); break;
		case	63 : /* zwin_radio(%,%,%,%,%,%) */
			result=(*DynamicLibrary->fonction[63])(
				LdfParaWord(0),
				LdfParaWord(1),
				LdfParaWord(2),
				LdfParaWord(3),
				LdfParaWord(4),
				LdfParaWord(5)); break;
		case	64 : /* zwin_statusxy(%,%) */
			result=(*DynamicLibrary->fonction[64])(
				LdfParaWord(0),
				LdfParaWord(1)); break;
		case	65 : /* zwin_status_draw() */
			result=(*DynamicLibrary->fonction[65])(); break;
		case	66 : /* zwin_status($,%) */
			result=(*DynamicLibrary->fonction[66])(
				pptr[0],
				LdfParaWord(1)); break;
		case	67 : /* zwin_mousecursor(%) */
			result=(*DynamicLibrary->fonction[67])(
				LdfParaWord(0)); break;
		case	68 : /* zwin_askcursor(%) */
			result=(*DynamicLibrary->fonction[68])(
				LdfParaWord(0)); break;
		case	69 : /* %zwin_bbitmap(%,$,$,%) */
			result=(*DynamicLibrary->fonction[69])(
				LdfParaWord(0),
				pptr[1],
				pptr[2],
				LdfParaWord(3)); break;
		case	70 : /* %zwin_bitmap($,%,%,%,%) */
			result=(*DynamicLibrary->fonction[70])(
				pptr[0],
				LdfParaWord(1),
				LdfParaWord(2),
				LdfParaWord(3),
				LdfParaWord(4)); break;
		case	71 : /* zwin_actual(%,%,%,%) */
			result=(*DynamicLibrary->fonction[71])(
				LdfParaWord(0),
				LdfParaWord(1),
				LdfParaWord(2),
				LdfParaWord(3)); break;
		case	72 : /* %zwdll_load($) */
			result=(*DynamicLibrary->fonction[72])(
				pptr[0]); break;
		case	73 : /* zwdll_free() */
			result=(*DynamicLibrary->fonction[73])(); break;
		case	74 : /* zwin_hlift(%,%,%,%,%,%,%) */
			result=(*DynamicLibrary->fonction[74])(
				LdfParaWord(0),
				LdfParaWord(1),
				LdfParaWord(2),
				LdfParaWord(3),
				LdfParaWord(4),
				LdfParaWord(5),
				LdfParaWord(6)); break;
		case	75 : /* %zwin_alone($) */
			result=(*DynamicLibrary->fonction[75])(
				pptr[0]); break;
		case	76 : /* %zchdir($) */
			result=(*DynamicLibrary->fonction[76])(
				pptr[0]); break;
		case	77 : /* %zwbmp_load(%,$,%) */
			result=(*DynamicLibrary->fonction[77])(
				LdfParaWord(0),
				pptr[1],
				LdfParaWord(2)); break;
		case	78 : /* zwbmp_free(%) */
			result=(*DynamicLibrary->fonction[78])(
				LdfParaWord(0)); break;
		case	79 : /* %zwin_bbmp(%,$,%,%) */
			result=(*DynamicLibrary->fonction[79])(
				LdfParaWord(0),
				pptr[1],
				LdfParaWord(2),
				LdfParaWord(3)); break;
		case	80 : /* %zwin_bmp(%,%,%,%,%) */
			result=(*DynamicLibrary->fonction[80])(
				LdfParaWord(0),
				LdfParaWord(1),
				LdfParaWord(2),
				LdfParaWord(3),
				LdfParaWord(4)); break;
		case	81 : /* %zzwin_version() */
			result=(*DynamicLibrary->fonction[81])(); break;
		case	82 : /* zzwin_clear($,%,%,%,%) */
			result=(*DynamicLibrary->fonction[82])(
				pptr[0],
				LdfParaWord(1),
				LdfParaWord(2),
				LdfParaWord(3),
				LdfParaWord(4)); break;
		case	83 : /* zzprint_title(%,%,%,$) */
			result=(*DynamicLibrary->fonction[83])(
				LdfParaWord(0),
				LdfParaWord(1),
				LdfParaWord(2),
				pptr[3]); break;
		case	84 : /* zzwinmove(%,%,%,%,%,%) */
			result=(*DynamicLibrary->fonction[84])(
				LdfParaWord(0),
				LdfParaWord(1),
				LdfParaWord(2),
				LdfParaWord(3),
				LdfParaWord(4),
				LdfParaWord(5)); break;
		case	85 : /* zzwinmoveable(%,%,%,%) */
			result=(*DynamicLibrary->fonction[85])(
				LdfParaWord(0),
				LdfParaWord(1),
				LdfParaWord(2),
				LdfParaWord(3)); break;
		case	86 : /* zwin_tabview(%,%,%,%,%,$,%,$) */
			result=(*DynamicLibrary->fonction[86])(
				LdfParaWord(0),
				LdfParaWord(1),
				LdfParaWord(2),
				LdfParaWord(3),
				LdfParaWord(4),
				pptr[5],
				LdfParaWord(6),
				pptr[7]); break;
		case	87 : /* zzgetmaxy(%?,%?) */
			result=(*DynamicLibrary->fonction[87])(
				pptr[0],
				pptr[1]); break;
		case	88 : /* %zzfont_choose($) */
			result=(*DynamicLibrary->fonction[88])(
				pptr[0]); break;
		case	89 : /* %zzfont_create(%,$) */
			result=(*DynamicLibrary->fonction[89])(
				LdfParaWord(0),
				pptr[1]); break;
		case	90 : /* zzfont_delete(%) */
			result=(*DynamicLibrary->fonction[90])(
				LdfParaWord(0)); break;
		case	91 : /* zzwin_title(%,%,%,$,%,%,%) */
			result=(*DynamicLibrary->fonction[91])(
				LdfParaWord(0),
				LdfParaWord(1),
				LdfParaWord(2),
				pptr[3],
				LdfParaWord(4),
				LdfParaWord(5),
				LdfParaWord(6)); break;
		case	92 : /* zzprintl(%,$,%) */
			result=(*DynamicLibrary->fonction[92])(
				LdfParaWord(0),
				pptr[1],
				LdfParaWord(2)); break;
		case	93 : /* %zzw_getcolor(%,%) */
			result=(*DynamicLibrary->fonction[93])(
				LdfParaWord(0),
				LdfParaWord(1)); break;
		case	94 : /* zzw_color(%,%,%) */
			result=(*DynamicLibrary->fonction[94])(
				LdfParaWord(0),
				LdfParaWord(1),
				LdfParaWord(2)); break;
		case	95 : /* zzw_brush(%,%,%,%) */
			result=(*DynamicLibrary->fonction[95])(
				LdfParaWord(0),
				LdfParaWord(1),
				LdfParaWord(2),
				LdfParaWord(3)); break;
		case	96 : /* zzw_pen(%,%,%,%,%) */
			result=(*DynamicLibrary->fonction[96])(
				LdfParaWord(0),
				LdfParaWord(1),
				LdfParaWord(2),
				LdfParaWord(3),
				LdfParaWord(4)); break;
		case	97 : /* zzw_point(%,%) */
			result=(*DynamicLibrary->fonction[97])(
				LdfParaWord(0),
				LdfParaWord(1)); break;
		case	98 : /* zzw_line(%,%,%,%) */
			result=(*DynamicLibrary->fonction[98])(
				LdfParaWord(0),
				LdfParaWord(1),
				LdfParaWord(2),
				LdfParaWord(3)); break;
		case	99 : /* zzw_rectangle(%,%,%,%) */
			result=(*DynamicLibrary->fonction[99])(
				LdfParaWord(0),
				LdfParaWord(1),
				LdfParaWord(2),
				LdfParaWord(3)); break;
		case	100 : /* zzw_roundrect(%,%,%,%,%,%) */
			result=(*DynamicLibrary->fonction[100])(
				LdfParaWord(0),
				LdfParaWord(1),
				LdfParaWord(2),
				LdfParaWord(3),
				LdfParaWord(4),
				LdfParaWord(5)); break;
		case	101 : /* zzw_ellipse(%,%,%,%) */
			result=(*DynamicLibrary->fonction[101])(
				LdfParaWord(0),
				LdfParaWord(1),
				LdfParaWord(2),
				LdfParaWord(3)); break;
		case	102 : /* zzw_pie(%,%,%,%,%,%,%,%) */
			result=(*DynamicLibrary->fonction[102])(
				LdfParaWord(0),
				LdfParaWord(1),
				LdfParaWord(2),
				LdfParaWord(3),
				LdfParaWord(4),
				LdfParaWord(5),
				LdfParaWord(6),
				LdfParaWord(7)); break;
		case	103 : /* zzw_trapez(%,%,%,%,%,%,%,%) */
			result=(*DynamicLibrary->fonction[103])(
				LdfParaWord(0),
				LdfParaWord(1),
				LdfParaWord(2),
				LdfParaWord(3),
				LdfParaWord(4),
				LdfParaWord(5),
				LdfParaWord(6),
				LdfParaWord(7)); break;
		case	104 : /* zzw_printxy(%,%,%,$) */
			result=(*DynamicLibrary->fonction[104])(
				LdfParaWord(0),
				LdfParaWord(1),
				LdfParaWord(2),
				pptr[3]); break;
		case	105 : /* %zwin_xbmp(%,%,%,%,%,%,%) */
			result=(*DynamicLibrary->fonction[105])(
				LdfParaWord(0),
				LdfParaWord(1),
				LdfParaWord(2),
				LdfParaWord(3),
				LdfParaWord(4),
				LdfParaWord(5),
				LdfParaWord(6)); break;
		case	106 : /* %zzwin_nbbits() */
			result=(*DynamicLibrary->fonction[106])(); break;
		case	107 : /* zzdefault_font(%,%) */
			result=(*DynamicLibrary->fonction[107])(
				LdfParaWord(0),
				LdfParaWord(1)); break;
		case	108 : /* zzRGBcolor(%,%,%,%,%) */
			result=(*DynamicLibrary->fonction[108])(
				LdfParaWord(0),
				LdfParaWord(1),
				LdfParaWord(2),
				LdfParaWord(3),
				LdfParaWord(4)); break;
		case	109 : /* zzdefault_color(%,%,%,%) */
			result=(*DynamicLibrary->fonction[109])(
				LdfParaWord(0),
				LdfParaWord(1),
				LdfParaWord(2),
				LdfParaWord(3)); break;
		case	110 : /* zwin_vabutton(%,%,%) */
			result=(*DynamicLibrary->fonction[110])(
				LdfParaWord(0),
				LdfParaWord(1),
				LdfParaWord(2)); break;
		case	111 : /* zzwin_setpile(%,%,%,%,%,%) */
			result=(*DynamicLibrary->fonction[111])(
				LdfParaWord(0),
				LdfParaWord(1),
				LdfParaWord(2),
				LdfParaWord(3),
				LdfParaWord(4),
				LdfParaWord(5)); break;
		case	112 : /* %zsystem_menu() */
			result=(*DynamicLibrary->fonction[112])(); break;
		case	113 : /* zzreserve39() */
			result=(*DynamicLibrary->fonction[113])(); break;
		case	114 : /* zTraMsg(%,%,$,$) */
			result=(*DynamicLibrary->fonction[114])(
				LdfParaWord(0),
				LdfParaWord(1),
				pptr[2],
				pptr[3]); break;
		case	115 : /* zTraMsgInt(%,%,$,$,%) */
			result=(*DynamicLibrary->fonction[115])(
				LdfParaWord(0),
				LdfParaWord(1),
				pptr[2],
				pptr[3],
				LdfParaWord(4)); break;
		case	116 : /* %zPrlTst1(%) */
			result=(*DynamicLibrary->fonction[116])(
				LdfParaWord(0)); break;
		case	117 : /* %zPrlTst2(%) */
			result=(*DynamicLibrary->fonction[117])(
				LdfParaWord(0)); break;
		case	118 : /* %zPrlTst3(%) */
			result=(*DynamicLibrary->fonction[118])(
				LdfParaWord(0)); break;
		case	119 : /* %zManageLoadgo(%) */
			result=(*DynamicLibrary->fonction[119])(
				LdfParaWord(0)); break;
		case	120 : /* %zScreenSaver() */
			result=(*DynamicLibrary->fonction[120])(); break;
		case	121 : /* zTraDump(%,%,$,$,$,%) */
			result=(*DynamicLibrary->fonction[121])(
				LdfParaWord(0),
				LdfParaWord(1),
				pptr[2],
				pptr[3],
				pptr[4],
				LdfParaWord(5)); break;
		case	122 : /* zzreserve48() */
			result=(*DynamicLibrary->fonction[122])(); break;
		case	123 : /* zzreserve49() */
			result=(*DynamicLibrary->fonction[123])(); break;
		case	124 : /* zzreserve50() */
			result=(*DynamicLibrary->fonction[124])(); break;
		case	125 : /* zzreserve51() */
			result=(*DynamicLibrary->fonction[125])(); break;
		case	126 : /* zzreserve52() */
			result=(*DynamicLibrary->fonction[126])(); break;
		case	127 : /* zzreserve53() */
			result=(*DynamicLibrary->fonction[127])(); break;
		case	128 : /* zzreserve54() */
			result=(*DynamicLibrary->fonction[128])(); break;
		case	129 : /* zzreserve55() */
			result=(*DynamicLibrary->fonction[129])(); break;
		case	130 : /* zzreserve56() */
			result=(*DynamicLibrary->fonction[130])(); break;
		case	131 : /* zzreserve57() */
			result=(*DynamicLibrary->fonction[131])(); break;
		case	132 : /* zzreserve58() */
			result=(*DynamicLibrary->fonction[132])(); break;
		case	133 : /* zzreserve59() */
			result=(*DynamicLibrary->fonction[133])(); break;
		case	134 : /* zzreserve60() */
			result=(*DynamicLibrary->fonction[134])(); break;
		case	135 : /* zzreserve61() */
			result=(*DynamicLibrary->fonction[135])(); break;
		case	136 : /* zzreserve62() */
			result=(*DynamicLibrary->fonction[136])(); break;
		case	137 : /* zzreserve63() */
			result=(*DynamicLibrary->fonction[137])(); break;
		case	138 : /* zzreserve64() */
			result=(*DynamicLibrary->fonction[138])(); break;
		case	139 : /* zzreserve65() */
			result=(*DynamicLibrary->fonction[139])(); break;
		case	140 : /* zzreserve66() */
			result=(*DynamicLibrary->fonction[140])(); break;
		case	141 : /* zzreserve67() */
			result=(*DynamicLibrary->fonction[141])(); break;
		case	142 : /* zzreserve68() */
			result=(*DynamicLibrary->fonction[142])(); break;
		case	143 : /* zzreserve69() */
			result=(*DynamicLibrary->fonction[143])(); break;
		case	144 : /* zzreserve70() */
			result=(*DynamicLibrary->fonction[144])(); break;
		case	145 : /* zzreserve71() */
			result=(*DynamicLibrary->fonction[145])(); break;
		case	146 : /* zzreserve72() */
			result=(*DynamicLibrary->fonction[146])(); break;
		case	147 : /* zzreserve73() */
			result=(*DynamicLibrary->fonction[147])(); break;
		case	148 : /* zzreserve74() */
			result=(*DynamicLibrary->fonction[148])(); break;
		case	149 : /* zzreserve75() */
			result=(*DynamicLibrary->fonction[149])(); break;
		case	150 : /* zzreserve76() */
			result=(*DynamicLibrary->fonction[150])(); break;
		case	151 : /* zzreserve77() */
			result=(*DynamicLibrary->fonction[151])(); break;
		case	152 : /* zzreserve78() */
			result=(*DynamicLibrary->fonction[152])(); break;
		case	153 : /* zzreserve79() */
			result=(*DynamicLibrary->fonction[153])(); break;
		case	154 : /* zzreserve80() */
			result=(*DynamicLibrary->fonction[154])(); break;
		case	155 : /* zzreserve81() */
			result=(*DynamicLibrary->fonction[155])(); break;
		case	156 : /* zzreserve82() */
			result=(*DynamicLibrary->fonction[156])(); break;
		case	157 : /* zzreserve83() */
			result=(*DynamicLibrary->fonction[157])(); break;
		case	158 : /* zzreserve84() */
			result=(*DynamicLibrary->fonction[158])(); break;
		case	159 : /* zzreserve85() */
			result=(*DynamicLibrary->fonction[159])(); break;
		case	160 : /* zzreserve86() */
			result=(*DynamicLibrary->fonction[160])(); break;
		case	161 : /* zzreserve87() */
			result=(*DynamicLibrary->fonction[161])(); break;
		case	162 : /* zzreserve88() */
			result=(*DynamicLibrary->fonction[162])(); break;
		case	163 : /* zzreserve89() */
			result=(*DynamicLibrary->fonction[163])(); break;
		case	164 : /* zzreserve90() */
			result=(*DynamicLibrary->fonction[164])(); break;
		case	165 : /* zzreserve91() */
			result=(*DynamicLibrary->fonction[165])(); break;
		case	166 : /* zzreserve92() */
			result=(*DynamicLibrary->fonction[166])(); break;
		case	167 : /* zzreserve93() */
			result=(*DynamicLibrary->fonction[167])(); break;
		case	168 : /* zzreserve94() */
			result=(*DynamicLibrary->fonction[168])(); break;
		case	169 : /* zzreserve95() */
			result=(*DynamicLibrary->fonction[169])(); break;
		case	170 : /* zzreserve96() */
			result=(*DynamicLibrary->fonction[170])(); break;
		case	171 : /* zzreserve97() */
			result=(*DynamicLibrary->fonction[171])(); break;
		case	172 : /* zzreserve98() */
			result=(*DynamicLibrary->fonction[172])(); break;
		case	173 : /* zzreserve99() */
			result=(*DynamicLibrary->fonction[173])(); break;
		default	: result=138;
		break;
		}
	/* end */
	return(result);
}

/* Library Constructor */

public EXAWORD LdfBdaInitialise(
	BDA_INIT FAR PTR descriptor,
	EXAWORD dlength)
{
	int	i=0;
	rt_init = descriptor;
	function_counter=174;
	if (!(DynamicLibrary = InitRelais()))
		return(139);
	else	return(0);
}

#endif  /* __linbda__home_abal64_src_zgr_z_c__ */
/* End of File */
