
#define H_LAND  	136	/* nb de lignes de l'editeur	*/
#define W_LAND		84	/* nb de colonnes de l'editeur	*/


char landscape [H_LAND][W_LAND] =
       {
	{"                                                                                   "},
	{"/**************************************************************     	             "},
	{"* Exemple de traitement de la souris                          *     	             "},
	{"*-------------------------------------------------------------*     	             "},
	{"* Source : edit.c                                             *     	             "},
	{"*-------------------------------------------------------------*     	             "},
	{"* Version : 1.0                                               *     	             "},
	{"* Mise a jour le : 22/06/92  EDS (CERVIX)                     *     	             "},
	{"*                                                             *     	             "},
	{"***************************************************************/    	             "},
	{"                                                                    	             "},
	{"                                                                    	             "},
	{"                                                                    	             "},
	{"                                                                    	             "},
	{"/* includes sp‚cifiques fenetrage */                                	             "},
	{"                                                                    	             "},
	{"#include      \"sfundef.h\"                                         	             "},
	{"#include      \"bda.h\"                                             	             "},
	{"                                                                    	             "},
	{"#include      \"mouse.h\"                                           	             "},
	{"                                                                    	             "},
	{"                                                                    	             "},
	{"                                                                    	             "},
	{"/* defines relatifs mouse */                                        	             "},
	{"                                                                    	             "},
	{"#define EDIT_EVENTS   KEYBOARD+MOUSE_DOWN+MOUSE_UP+MOUSE_CLICK+     	             "},
	{"                      MOUSE_D_CLICK+MOUSE_M_W_DOWN+MOUSE_IS_DOWN    	             "},
	{"                                                                    	             "},
	{"                                                                    	             "},
	{"#define NO_REGION     0                                             	             "},
	{"#define INSIDE        1                                             	             "},
	{"#define CADRE_GAUCHE  2                                             	             "},
	{"#define CADRE_DROIT   3                                             	             "},
	{"#define CADRE_HAUT    4                                             	             "},
	{"#define CADRE_BAS     5                                             	             "},
	{"                                                                    	             "},
	{"                                                                    	             "},
	{"                                                                    	             "},
	{"                                                                    	             "},
	{"/* Externes */                                                      	             "},
	{"                                                                    	             "},
	{"extern WITEM* WLOG[MAXFUN];                                         	             "},
	{"                                                                    	             "},
	{"extern EVENT_STR event;                                             	             "},
	{"                                                                    	             "},
	{"                                                                    	             "},
	{"                                                                    	             "},
	{"                                                                    	             "},
	{"                                                                    	             "},
	{"                                                                    	             "},
	{"                                                                    	             "},
	{"main()                                                              	             "},
	{"                                                                    	             "},
	{" {                                                                  	             "},
	{"  BYTE car, buff[10];                                               	             "},
	{"  WORD coder;                                                       	             "},
	{"  WORD plig, pcol, region, moving, s_col;                           	             "},
	{"  WORD top_v, top_h, maxi_v, maxi_h, nb_l, nb_c;                    	             "},
	{"  SWORD y_m, x_m;                                                   	             "},
	{"  WDESC_APP df1;                                                    	             "},
	{"  WORD f1;                                                          	             "},
	{"  WORD lng;                                                         	             "},
	{"  BYTE retour;                                                      	             "},
	{"  WITEM	*wi;                                                  	             "},
	{"  WDESC_PTR wd;                                                     	             "},
	{"                                                                    	             "},
	{"                                                                    	             "},
	{"                                                                    	             "},
	{"  coder = sfinit(\"stf\");                                          	             "},
	{"                                                                    	             "},
	{"  if((coder != 0) && (coder != 40))                                 	             "},
	{"    {                                                               	             "},
	{"     printf(\"Erreur INIT %d\",coder);                              	             "},
	{"     return(NULL);                                                  	             "},
	{"    }                                                               	             "},
	{"                                                                    	             "},
	{"  nb_l = 10;                                                        	             "},
	{"  nb_c = 40;                                                        	             "},
	{"                                                                    	             "},
	{"  plig = 5;                                                         	             "},
	{"  pcol = 25;                                                        	             "},
	{"                                                                    	             "},
	{"                                                                    	             "},
	{"  /* creation de la fenetre */                                      	             "},
	{"  df1.Amere_nbr = 0;                                                	             "},
	{"  df1.Apos_lig = plig;                                              	             "},
	{"  df1.Apos_col = pcol;                                              	             "},
	{"  df1.Anb_lig = nb_l;                                               	             "},
	{"  df1.Anb_col = nb_c;                                               	             "},
	{"  df1.Aatb_vid = NORMAL;                                            	             "},
	{"  df1.Aatbcol_text = BLANC_INT;                                     	             "},
	{"  df1.Aatbcol_fond = GRIS;                                          	             "},
	{"  df1.Acontrol = CAD1;                                              	             "},
	{"  df1.Aln_tit = 6;                                                  	             "},
	{"  strcpy(df1.Atitre,\"coucou\");                                    	             "},
	{"                                                                    	             "},
	{"  coder = wcreatc(&f1,&df1);                                        	             "},
	{"  if(coder != 0)                                                    	             "},
	{"    {                                                               	             "},
	{"     printf(\"Erreur CREAT no %d\",coder);                          	             "},
	{"     return;                                                        	             "},
	{"    }                                                              	             "},
	{"                                                                    	             "},
	{"  /* on recupere le descripteur interne de la fenetre */            	             "},
	{"  wi = WLOG[f1-1];                                                  	             "},
	{"  wd = wi->wdesc_ptr;                                               	             "},
	{"                                                                    	             "},
	{"                                                                    	             "},
	{"  /* Ajout des scroll bars */                                       	             "},
	{"  add_scroll_bar(f1, 2);                                            	             "},
	{"  add_scroll_bar(f1, 1);                                            	             "},
	{"                                                                    	             "},
	{"  top_v = 1;                                                        	             "},
	{"  top_h = 1;                                                        	             "},
	{"  maxi_v = 20;                                                      	             "},
	{"  maxi_h = 60;                                                      	             "},
	{"                                                                    	             "},
	{"  wgel(f1);                                                         	             "},
	{"  update_scroll_bar(f1, 2, maxi_v, top_v);                          	             "},
	{"  update_scroll_bar(f1, 1, maxi_h, top_h);                          	             "},
	{"  wvis(f1);                                                         	             "},
	{"                                                                    	             "},
	{"                                                                    	             "},
	{"  /* fenetre mouse_sensitive */                                     	             "},
	{"  put_item_mouse_list(f1);                                          	             "},
	{"                                                                    	             "},
	{"                                                                    	             "},
	{"  /* Boucle de traitement des event */                              	             "},
	{"                                                                    	             "},
	{"  while(TRUE)                                                       	             "},
	{"    {                                                               	             "},
	{"     if(event.event == NO_EVENT)                                    	             "},
	{"       wait_eventc(EDIT_EVENTS, &event);                            	             "},
	{"                                                                    	             "},
	{"     if(event.event == KEYBOARD)                                    	             "},
	{"       car = event.arg;                                             	             "}
