/* File generated by /opt/prologue/bin/linbda Version 1.1b.0.01 : asfun.def -> asfun.c */
#ifndef __linbda_asfun_c__
#define __linbda_asfun_c__
#include <stdio.h>
#include "ldfbda.h"

static BDA * DynamicLibrary;
	LPBDA_INIT	rt_init;
	BDA_INIT	v_rt_init;
	BDA_ARG rt_arg;


static int function_counter=0;
/* ABAL Word Convertor */
static EXAWORD LdfAbalByte(char FAR PTR bptr)
{
	return(*bptr);
}

static EXAWORD LdfAbalWord(BYTE FAR PTR wptr)
{
	return(((*wptr<< 8) | *(wptr+1)));
}

static EXAWORD LdfAbalLong(BYTE FAR PTR wptr)
{
	return( (LdfAbalWord( wptr ) << 16 ) | ( LdfAbalWord((wptr+2)) & 0xFFFF )) );
}

#define LdfParaLong(n) ( tptr[n] == 1 ?	LdfAbalWord(pptr[n]) : ( tptr[n] == 0 ? LdfAbalByte(pptr[n]) : LdfAbalLong(pptr[n])	))
#define LdfParaWord(n) ( tptr[n] == 1 ?	(LdfAbalWord(pptr[n])&0xFFFF) : ( tptr[n] == 0 ? (LdfAbalByte(pptr[n])&0xFFFF) : (LdfAbalLong(pptr[n])&0xFFFF)	))
#define LdfParaByte(n) ( tptr[n] == 1 ?	(LdfAbalWord(pptr[n])&0x00FF) : ( tptr[n] == 0 ? (LdfAbalByte(pptr[n])&0xFFFF) : (LdfAbalLong(pptr[n])&0x00FF)	))

static BYTE PTR function_names[256];
static int trace_name=(char*)0;
static int trace_handle=(FILE*)0;
extern long time(long*);

/* Trace Activation */
static void start_trace()
{
	trace_name = getenv("ASFUN_TRACE");
	if ( trace_name != (char *) 0 ) {
		trace_handle=fopen(trace_name,"w");
		}
	return;
}

/* Trace Write */
static void write_trace(char * mptr)
{
	if ( trace_handle != (FILE*)0) {
		fprintf(trace_handle,mptr);
		fprintf(trace_handle,"\r\n");
		}
	return;
}

/* Trace Result */
static void trace_result(EXAWORD result)
{
	if ( trace_handle != (FILE*)0) {
		fprintf(trace_handle,"RETURN: %u \r\n",result);
		}
	return;
}

/* Trace Call */
static void trace_call(
	EXAWORD fid,
	EXAWORD argc,
	BYTE FAR tptr[],
	VOID FAR PTR FAR pptr[],
	EXAWORD FAR wptr[])
{
	char * bptr;
	int	i=0;
	int	j=0;
	if ( trace_handle != (FILE*)0) {
			fprintf(trace_handle,"[%lu] ",time((long*)0));
		if ( function_names[fid] != (char *) 0) {
			fprintf(trace_handle,"(%s)",function_names[fid]);
			}
		else	{
			fprintf(trace_handle,"(call %u)",fid);
			}
		for (i=0; i < argc; i++) {
			switch(tptr[i]) {
				case 0x0080 : 
					fprintf(trace_handle,"\t(*b=%x)\r\n",*((bptr=pptr[i])));
					break;
				case 0  : 
					fprintf(trace_handle,"\t(b=%x)\r\n",*((bptr=pptr[i])));
					break;
				case 0x0081 : 
					fprintf(trace_handle,"\t(*w=%x)\r\n",LdfAbalWord(pptr[i]));
					break;
				case 1  : 
					fprintf(trace_handle,"\t(w=%x)\r\n",LdfAbalWord(pptr[i]));
					break;
				case 2  : 
				case 3  : 
				case 0x0082 : 
				case 0x0083 : 
					fprintf(trace_handle,"\t(*=");
					for (bptr=pptr[i],j=0;j<wptr[i];j++) {
						fprintf(trace_handle,"%x ",(*(bptr+j)&0x00FF));
						if ((j % 20) == 19) {
							fprintf(trace_handle,"\r\n");
							}
						}
					fprintf(trace_handle,")\r\n");
				};
			}
		fprintf(trace_handle,"\r\n");
		}
	return;
}

/* Trace Closure */
static void close_trace()
{
	if ( trace_handle != (FILE*)0) {
		fclose(trace_handle);
		trace_handle=(FILE*)0;
		}
	return;
}

/* Library Destructor */
EXAWORD LdfBdaTerminate()
{
	write_trace("LdfBdaTerminate()");
	close_trace();
	if (DynamicLibrary->fin != (VOID (FAR PTR)()) 0)
		 (*DynamicLibrary->fin)();
	return(0);
}

/* Library Call Through */
EXAWORD LdfBdaExecute(
	EXAWORD fid,
	EXAWORD argc,
	BYTE FAR tptr[],
	VOID FAR PTR FAR pptr[],
	EXAWORD FAR wptr[])
{
	EXAWORD	result=0;	rt_arg.c=argc; rt_arg.v=pptr;
	rt_arg.l=wptr; rt_arg.t=tptr;
	if ( trace_handle != (FILE*)0) {
	trace_call(fid,argc,tptr,pptr,wptr);
		}
	/* version = 1,num */
	/* Explicite Numbering */
	/* runtime = "asfun" */
	/* 0: %winit(#,#,#,#,#) */
	/* 1: %wcreat(%? , $) */
	/* 2: %wsup(%) */
	/* 3: %wwrite(%,%,$) */
	/* 4: %wselect(%) */
	/* 5: %winv(%) */
	/* 6: %wvis(%) */
	/* 7: %wfgen(%,%) */
	/* 8: %watb(%,#,#,#) */
	/* 9: %wposcur(%,%,%) */
	/* 10:%wimpl(%) */
	/* 11:%wgel(%) */
	/* 12:%wfend() */
	/* 13:%wsetatb(%,#,#,#,%,%,%,%) */
	/* 14: %sf_init($) */
	/* 15:%sl_activ() */
	/* 16:%sl_mess(#,#,$) */
	/* 17:%sl_inv() */
	/* 18:%sl_desac() */
	/* 19:%menu_creat(#,$,.) */
	/* 20:%menu_option(#,#,$,$,$) */
	/* 21:%menu_sep(#,#) */
	/* 22:%menu_modif_opt(#,#,#,$,$,$) */
	/* 23:%menu_latt_opt(#,#,#?,#?,#?,.) */
	/* 24:%menu_matt_opt(#,#,#,#,#) */
	/* 25:%menu_blank_opt(#,#) */
	/* 26:%menu_vis(#,#,#) */
	/* 27:%menu(#,#,#?,#?,$?,.?) */
	/* 28:%menu_inv(#) */
	/* 29:%menu_sup(#) */
	/* 30:%list_creat(#,$,.) */
	/* 31:%listmul_creat(#,$,.) */
	/* 32:%list_element(#,%?,#,#,$,$) */
	/* 33:%list_read_elt(#,%,#?,#?,$?) */
	/* 34:%list_down(#,%?,#?,#?,$?) */
	/* 35:%list_up(#,%?,#?,#?,$?) */
	/* 36:%list_matt_elt(#,%,#,#,.) */
	/* 37:%list_close(#) */
	/* 38:%list_vis(#,%,%,.) */
	/* 39:%list(#,%?,%?,#?,$?,.?) */
	/* 40:%list_inv(#) */
	/* 41:%list_sup(#) */
	/* 42:%bvalid_spc($,$,#?) */
	/* 43:%bvalid(#,#?) */
	/* 44:%sf_end() */
	/* 45:%wfmod(%,%,%?,$?,#,.?) */
	/* 46:%help_activ(#,$) */
	/* 47:%help($) */
	/* 48:%help_desac() */
	/* 49:%help_def($) */
	/* 50:%wget_impl(%?) */
	/* 51:%bd_creat(%?,%,%,%,%,%,.) */
	/* 52:%bd_insert(%,%,%,%,.) */
	/* 53:%bd_use(%,%,%?,.?) */
	/* 54:%bd_inv(%) */
	/* 55:%bd_sup(%) */
	/* 56:%bd_putdata(%,$) */
	/* 57:%bd_getdata(%,$?) */
	/* 58:%wexit(%) */
	/* 59:%wrefresh() */
	/* 60:%menu_way(#?,$?) */
	/* 61:%swcreat(%?,%,%,%,%,.) */
	/* 62:%wcadre(%,#,.) */
	/* 63:%wtitre(%,#,#,#,.) */
	/* 64:%wmove(%,%,%) */
	/* 65:%listel_del(#,%) */
	/* 66:%listel_ins(#,%?,#,#,$,$) */
	/* 67:%set_tch_esc(#,$) */
	/* 68:%winfo(%,$?) */
	/* 69:%get_style(#,$?) */
	/* 70:%set_style(#,$) */
	/* 71:%wlangue(#) */
	/* 72:%asfvers($?) */
	/* 88:%who_is_there(%,%,%?,%?) */
	/* 89:%rlecomp($,$,%) */
	/* 90:%rledecomp($,$,%) */
	if (fid > function_counter) result=138; else result=(*DynamicLibrary->fonction[fid])(pptr);
	/* end */
	if ( trace_handle != (FILE*)0) {
		trace_result( result );
		}
	return(result);
}

/* Library Constructor */

EXAWORD LdfBdaInitialise(
	BDA_INIT FAR PTR descriptor,
	EXAWORD dlength)
{
	int	i=0;
	rt_init = descriptor;
	function_counter=90;
	function_names[0] = "0: %winit(#,#,#,#,#)";
	function_names[1] = "1: %wcreat(%? , $)";
	function_names[2] = "2: %wsup(%)";
	function_names[3] = "3: %wwrite(%,%,$)";
	function_names[4] = "4: %wselect(%)";
	function_names[5] = "5: %winv(%)";
	function_names[6] = "6: %wvis(%)";
	function_names[7] = "7: %wfgen(%,%)";
	function_names[8] = "8: %watb(%,#,#,#)";
	function_names[9] = "9: %wposcur(%,%,%)";
	function_names[10] = "10:%wimpl(%)";
	function_names[11] = "11:%wgel(%)";
	function_names[12] = "12:%wfend()";
	function_names[13] = "13:%wsetatb(%,#,#,#,%,%,%,%)";
	function_names[14] = "14: %sf_init($)";
	function_names[15] = "15:%sl_activ()";
	function_names[16] = "16:%sl_mess(#,#,$)";
	function_names[17] = "17:%sl_inv()";
	function_names[18] = "18:%sl_desac()";
	function_names[19] = "19:%menu_creat(#,$,.)";
	function_names[20] = "20:%menu_option(#,#,$,$,$)";
	function_names[21] = "21:%menu_sep(#,#)";
	function_names[22] = "22:%menu_modif_opt(#,#,#,$,$,$)";
	function_names[23] = "23:%menu_latt_opt(#,#,#?,#?,#?,.)";
	function_names[24] = "24:%menu_matt_opt(#,#,#,#,#)";
	function_names[25] = "25:%menu_blank_opt(#,#)";
	function_names[26] = "26:%menu_vis(#,#,#)";
	function_names[27] = "27:%menu(#,#,#?,#?,$?,.?)";
	function_names[28] = "28:%menu_inv(#)";
	function_names[29] = "29:%menu_sup(#)";
	function_names[30] = "30:%list_creat(#,$,.)";
	function_names[31] = "31:%listmul_creat(#,$,.)";
	function_names[32] = "32:%list_element(#,%?,#,#,$,$)";
	function_names[33] = "33:%list_read_elt(#,%,#?,#?,$?)";
	function_names[34] = "34:%list_down(#,%?,#?,#?,$?)";
	function_names[35] = "35:%list_up(#,%?,#?,#?,$?)";
	function_names[36] = "36:%list_matt_elt(#,%,#,#,.)";
	function_names[37] = "37:%list_close(#)";
	function_names[38] = "38:%list_vis(#,%,%,.)";
	function_names[39] = "39:%list(#,%?,%?,#?,$?,.?)";
	function_names[40] = "40:%list_inv(#)";
	function_names[41] = "41:%list_sup(#)";
	function_names[42] = "42:%bvalid_spc($,$,#?)";
	function_names[43] = "43:%bvalid(#,#?)";
	function_names[44] = "44:%sf_end()";
	function_names[45] = "45:%wfmod(%,%,%?,$?,#,.?)";
	function_names[46] = "46:%help_activ(#,$)";
	function_names[47] = "47:%help($)";
	function_names[48] = "48:%help_desac()";
	function_names[49] = "49:%help_def($)";
	function_names[50] = "50:%wget_impl(%?)";
	function_names[51] = "51:%bd_creat(%?,%,%,%,%,%,.)";
	function_names[52] = "52:%bd_insert(%,%,%,%,.)";
	function_names[53] = "53:%bd_use(%,%,%?,.?)";
	function_names[54] = "54:%bd_inv(%)";
	function_names[55] = "55:%bd_sup(%)";
	function_names[56] = "56:%bd_putdata(%,$)";
	function_names[57] = "57:%bd_getdata(%,$?)";
	function_names[58] = "58:%wexit(%)";
	function_names[59] = "59:%wrefresh()";
	function_names[60] = "60:%menu_way(#?,$?)";
	function_names[61] = "61:%swcreat(%?,%,%,%,%,.)";
	function_names[62] = "62:%wcadre(%,#,.)";
	function_names[63] = "63:%wtitre(%,#,#,#,.)";
	function_names[64] = "64:%wmove(%,%,%)";
	function_names[65] = "65:%listel_del(#,%)";
	function_names[66] = "66:%listel_ins(#,%?,#,#,$,$)";
	function_names[67] = "67:%set_tch_esc(#,$)";
	function_names[68] = "68:%winfo(%,$?)";
	function_names[69] = "69:%get_style(#,$?)";
	function_names[70] = "70:%set_style(#,$)";
	function_names[71] = "71:%wlangue(#)";
	function_names[72] = "72:%asfvers($?)";
	function_names[73] = (char*)0;
	function_names[74] = (char*)0;
	function_names[75] = (char*)0;
	function_names[76] = (char*)0;
	function_names[77] = (char*)0;
	function_names[78] = (char*)0;
	function_names[79] = (char*)0;
	function_names[80] = (char*)0;
	function_names[81] = (char*)0;
	function_names[82] = (char*)0;
	function_names[83] = (char*)0;
	function_names[84] = (char*)0;
	function_names[85] = (char*)0;
	function_names[86] = (char*)0;
	function_names[87] = (char*)0;
	function_names[88] = "88:%who_is_there(%,%,%?,%?)";
	function_names[89] = "89:%rlecomp($,$,%)";
	start_trace();
	write_trace("LdfBdaInitialise()");
	if (!(DynamicLibrary = InitRelais()))
		return(139);
	else	return(0);
}

#endif  /* __linbda_asfun_c__ */
/* End of File */
