! include $(ABAL)/common/allocate.def
! include $(ABAL)/common/common.def
! include $(ABAL)/common/host.def
! include $(ABAL)/common/libconv.def

SRC      = $(ABAL)/src/otr/
LIB      = /lib


OTR   = otr16
otr   = /home/a3/bin/$(OTR)
OTR   = $(ABAL)/bin/otr16
CTR   = ctr16
ctr   = /home/a3/bin/$(CTR)
CTR   = $(ABAL)/bin/ctr16

! include otr.mf
! make
! include ctr.mf
! make
! error thats all
! include jtr.mf
! make



