/* File generated by /opt/prologue/bin/linbda Version 1.1b.0.03 : /home/Dev/abal32/src/printer/printer.def -> /home/Dev/abal32/src/printer/printer.c */
#ifndef __linbda__home_Dev_abal32_src_printer_printer_c__
#define __linbda__home_Dev_abal32_src_printer_printer_c__
#include <stdio.h>
#include <setjmp.h>
#include "ldfbda.h"

static BDA * DynamicLibrary;
	LPBDA_INIT	rt_init;
	BDA_INIT	v_rt_init;
	BDA_ARG rt_arg;

/* ABAL Runtime Error Trap */
static jmp_buf rt_error_context;
VOID rt_error(EXAWORD evalue) { 
	longjmp(rt_error_context,evalue);
	return;
}

static int function_counter=0;
/* ABAL Word Convertor */
static EXAWORD LdfAbalByte(char FAR PTR bptr)
{
	return(*bptr);
}

static EXAWORD LdfAbalWord(BYTE FAR PTR wptr)
{
	return(((*wptr<< 8) | *(wptr+1)));
}

#define LdfParaWord(n) ( tptr[n] == 1 ? LdfAbalWord(pptr[n]) : LdfAbalByte(pptr[n]) )
#define LdfParaByte(n) ( tptr[n] == 1 ? (LdfAbalWord(pptr[n])&0x00FF) : LdfAbalByte(pptr[n]) )
/* Library Destructor */
EXAWORD LdfBdaTerminate()
{
	if (DynamicLibrary->fin != (VOID (FAR PTR)()) 0)
		 (*DynamicLibrary->fin)();
	return(0);
}

/* Library Call Through */
EXAWORD LdfBdaExecute(
	EXAWORD fid,
	EXAWORD argc,
	BYTE FAR tptr[],
	VOID FAR PTR FAR pptr[],
	EXAWORD FAR wptr[],
	EXAWORD FAR * eptr)
{
	EXAWORD	result=0;
	rt_arg.c=argc; rt_arg.v=pptr;
	rt_arg.l=wptr; rt_arg.t=tptr;
	if ((result=setjmp(rt_error_context))!=0) {
		if ( eptr != (EXAWORD FAR *) 0) *eptr = result;
		return( result );
		}
	/* Version = 1 */
	/* Runtime = "printer" */
	switch ( fid ) {
		case	0 : /* % DriverInitialise($?,%,%,%,%) */
			result=(*DynamicLibrary->fonction[0])(
				pptr[0],
				LdfParaWord(1),
				LdfParaWord(2),
				LdfParaWord(3),
				LdfParaWord(4)); break;
		case	1 : /* % DriverColours() */
			result=(*DynamicLibrary->fonction[1])(); break;
		case	2 : /* % DriverConnect($,$,$) */
			result=(*DynamicLibrary->fonction[2])(
				pptr[0],
				pptr[1],
				pptr[2]); break;
		case	3 : /* % DriverStartRaster($?) */
			result=(*DynamicLibrary->fonction[3])(
				pptr[0]); break;
		case	4 : /* % DriverPrintRow($?,$) */
			result=(*DynamicLibrary->fonction[4])(
				pptr[0],
				pptr[1]); break;
		case	5 : /* % DriverEndRaster($?) */
			result=(*DynamicLibrary->fonction[5])(
				pptr[0]); break;
		case	6 : /* % DriverLiberate($?) */
			result=(*DynamicLibrary->fonction[6])(
				pptr[0]); break;
		default	: result=138;
		break;
		}
	/* End */
	return(result);
}

/* Library Constructor */

EXAWORD LdfBdaInitialise(
	BDA_INIT FAR PTR descriptor,
	EXAWORD dlength)
{
	int	i=0;
	rt_init = descriptor;
	function_counter=7;
	if (!(DynamicLibrary = InitRelais()))
		return(139);
	else	return(0);
}

#endif  /* __linbda__home_Dev_abal32_src_printer_printer_c__ */
/* End of File */
