/* File generated by D:\WORK\SOURCES\HTML\LINBDA.EXE : scream.def -> scream.c */
#ifndef __linbda_scream_c__
#define __linbda_scream_c__
#include <stdio.h>
#include "ldfbda.h"

extern BDA desrt;

static int function_counter=0;
/* ABAL Word Convertor */
static WORD LdfAbalWord(BYTE FAR PTR wptr)
{
	return(((*wptr<< 8) | *(wptr+1)));
}


static int trace_name=(char*)0;

static int trace_handle=(FILE*)0;
/* Trace Activation */
static void start_trace()
{
	trace_name = getenv("LINBDA_OUTPUT");
	trace_handle=fopen(trace_name,"w");
	return;
}

/* Trace Write */
static void write_trace(char * mptr)
{
	if ( trace_handle != (FILE*)0) {
		fprintf(trace_handle,mptr);
		fprintf(trace_handle,"\n");
		}
	return;
}

/* Trace Call */
static void trace_call(
	WORD fid,
	WORD argc,
	BYTE FAR tptr[],
	VOID FAR PTR FAR pptr[],
	WORD FAR wptr[])
{
	char * bptr;
	int	i=0;
	int	j=0;
	if ( trace_handle != (FILE*)0) {
		fprintf(trace_handle,"(call %u)",fid);
		for (i=0; i < argc; i++) {
			switch(tptr[i]) {
				case 8  : 
				case 0  : 
					fprintf(trace_handle,"\t(b=%x)\n",*((bptr=pptr[i])));
					break;
				case 9  : 
				case 1  : 
					fprintf(trace_handle,"\t(w=%x)\n",LdfAbalWord(pptr[i]));
					break;
				case 2  : 
				case 3  : 
				case 10 : 
				case 11 : 
					fprintf(trace_handle,"\t(*=");
					for (bptr=pptr[i],j=0;j<wptr[i];j++) {
						fprintf(trace_handle,"%x ",*(bptr+j));
						}
					fprintf(trace_handle,")\n");
				};
			}
		fprintf(trace_handle,"\n");
		}
	return;
}

/* Trace Closure */
static void close_trace()
{
	if ( trace_handle != (FILE*)0) {
		fclose(trace_handle);
		trace_handle=(FILE*)0;
		}
	return;
}

/* Library Destructor */
WORD LdfBdaTerminate()
{
	write_trace("LdfBdaTerminate()");
	close_trace();
	if (desrt.fin != (VOID (FAR PTR)()) 0)
		 (*desrt.fin)();
	return(0);
}

/* Library Call Through */
WORD LdfBdaExecute(
	WORD fid,
	WORD argc,
	BYTE FAR tptr[],
	VOID FAR PTR FAR pptr[],
	WORD FAR wptr[])
{
	trace_call(fid,argc,tptr,pptr,wptr);
	/* Version = 1 */
	/* Runtime = "scream" */
	/* % initialisepixel( % ) */
	/* % liberatepixel() */
	/* % putpixel(%,%,%) */
	/* % getpixel(%,%) */
	/* % filzone(%,%,%,%,%) */
	/* % putzone(%,%,%,%,$) */
	/* % getzone(%,%,%,%,$?) */
	/* % mixzone(%,%,%,%,$) */
	/* % swapzone(%,%,%,%,$?) */
	/* % userware(%,%,%,%,$) */
	/* % hardware() */
	/* % testware() */
	/* % cicofont() */
	/* % cicocurser() */
	/* % cicocolour() */
	/* % cicopalette( ... ) */
	/* % cicoatribut( ... ) */
	/* % cicosetstyle( ... ) */
	/* % cicomargin( ... ) */
	/* % cicoshadow( ... ) */
	/* % loadfont( ... ) */
	/* % loadguifont( ... ) */
	/* % use_base_font(%) */
	/* % fonted_text( ... ) */
	/* % cicotext( ... ) */
	/* % basefontcolumns() */
	/* % basefontlines() */
	/* % get_base_font_width() */
	/* % get_base_font_height() */
	/* % hardcolumns() */
	/* % hardrows() */
	/* % pixelputc( % ) */
	/* % relief(%,%,%,%,%,%,%) */
	/* % window( %,%,%,%,%,$,% ) */
	if (fid < function_counter) return((*desrt.fonction[fid])(pptr)); else return(138);
	/* End */
	return(0);
}

/* Library Constructor */

WORD LdfBdaInitialise(
	BDA_INIT FAR PTR descriptor,
	WORD dlength)
{
	function_counter=0;
	start_trace();
	write_trace("LdfBdaInitialise()");
	InitRelais();
	return(0);
}

#endif  /* __linbda_scream_c__ */
/* End of File */
