# transfer of production sources from production area to this directory
# ---------------------------------------------------------------------
SP01 = $(ABAL)/src/xml/

methmenu.c:  $(SP01)methmenu.c  
	cp $* $@
editmenu.c:  $(SP01)editmenu.c  
	cp $* $@
evenmenu.c:  $(SP01)evenmenu.c  
	cp $* $@
vmethopt.c:  $(SP01)vmethopt.c  
	cp $* $@
filemenu.c:  $(SP01)filemenu.c  
	cp $* $@
formmenu.c:  $(SP01)formmenu.c  
	cp $* $@
formmenu31e.c:  $(SP01)formmenu31e.c  
	cp $* $@
imagmenu.c:  $(SP01)imagmenu.c  
	cp $* $@
mainmenu.c:  $(SP01)mainmenu.c  
	cp $* $@
optimenu.c:  $(SP01)optimenu.c  
	cp $* $@
projmenu.c:  $(SP01)projmenu.c  
	cp $* $@
tracmenu.c:  $(SP01)tracmenu.c  
	cp $* $@
viewmenu.c:  $(SP01)viewmenu.c  
	cp $* $@
viewmenu32a.c:  $(SP01)viewmenu32a.c  
	cp $* $@
viewmenu31e.c:  $(SP01)viewmenu31e.c  
	cp $* $@
widgmenu.c:  $(SP01)widgmenu.c  
	cp $* $@

vaed.c:      $(SP01)vaed.c  
	cp $* $@
vcss.c:      $(SP01)vcss.c  
	cp $* $@
vyna.c:      $(SP01)vyna.c  
	cp $* $@
vstatus.c:   $(SP01)vstatus.c  
	cp $* $@
vconsult.c:   $(SP01)vconsult.c  
	cp $* $@
vnatrad.c:   $(SP01)vnatrad.c  
	cp $* $@
vlocate.c:   $(SP01)vlocate.c  
	cp $* $@
vgridlock.c:   $(SP01)vgridlock.c  
	cp $* $@
vfileref.c:   $(SP01)vfileref.c  
	cp $* $@
vfexport.c:   $(SP01)vfexport.c  
	cp $* $@
valign.c:    $(SP01)valign.c  
	cp $* $@
vorder.c:    $(SP01)vorder.c  
	cp $* $@
vshell.c:    $(SP01)vshell.c  
	cp $* $@
vphp.c:    $(SP01)vphp.c  
	cp $* $@
vlaser.c:    $(SP01)vlaser.c  
	cp $* $@
vcompose.c:  $(SP01)vcompose.c  
	cp $* $@
vcompare.c:  $(SP01)vcompare.c  
	cp $* $@
vnation.c:   $(SP01)vnation.c  
	cp $* $@
vhelper.c:   $(SP01)vhelper.c  
	cp $* $@
vaprod.c:    $(SP01)vaprod.c  
	cp $* $@
vpopup.c:    $(SP01)vpopup.c  
	cp $* $@
vcobprod.c:  $(SP01)vcobprod.c  
	cp $* $@
vcamera.c:   $(SP01)vcamera.c  
	cp $* $@
vcprod.c:    $(SP01)vcprod.c  
	cp $* $@
vcube.c:     $(SP01)vcube.c  
	cp $* $@
vtree.c:     $(SP01)vtree.c  
	cp $* $@
vseek.c:     $(SP01)vseek.c  
	cp $* $@
vwsgen.c:     $(SP01)vwsgen.c  
	cp $* $@
vfile.c:     $(SP01)vfile.c 
	cp $* $@
vcursor.c:   $(SP01)vcursor.c  
	cp $* $@
vpiece.c:   $(SP01)vpiece.c  
	cp $* $@
vdebug.c:    $(SP01)vdebug.c  
	cp $* $@
vedcmd.c:    $(SP01)vedcmd.c  
	cp $* $@
vexit.c:     $(SP01)vexit.c  
	cp $* $@
vfextr.c:    $(SP01)vfextr.c  
	cp $* $@
vfload.c:    $(SP01)vfload.c  
	cp $* $@
vform.c:     $(SP01)vform.c  
	cp $* $@
vform31e.c:     $(SP01)vform31e.c  
	cp $* $@
vmethod.c:   $(SP01)vmethod.c  
	cp $* $@
vfsave.c:    $(SP01)vfsave.c  
	cp $* $@
vtsave.c:    $(SP01)vtsave.c  
	cp $* $@
vfselect.c:  $(SP01)vfselect.c  
	cp $* $@
vhtml.c:     $(SP01)vhtml.c  
	cp $* $@
vwebgen.c:   $(SP01)vwebgen.c  
	cp $* $@
viload.c:    $(SP01)viload.c  
	cp $* $@
vimage.c:    $(SP01)vimage.c  
	cp $* $@
vimport.c:   $(SP01)vimport.c  
	cp $* $@
vintro.c:    $(SP01)vintro.c  
	cp $* $@
visave.c:    $(SP01)visave.c  
	cp $* $@
vlink.c:     $(SP01)vlink.c  
	cp $* $@
vload.c:     $(SP01)vload.c  
	cp $* $@
vmload.c:    $(SP01)vmload.c  
	cp $* $@
vmprod.c:    $(SP01)vmprod.c  
	cp $* $@
vmsave.c:    $(SP01)vmsave.c  
	cp $* $@
vamake.c:    $(SP01)vamake.c  
	cp $* $@
vpage.c:     $(SP01)vpage.c  
	cp $* $@
vparam.c:    $(SP01)vparam.c  
	cp $* $@
vrecrep.c:   $(SP01)vrecrep.c  
	cp $* $@
vrefer.c:    $(SP01)vrefer.c  
	cp $* $@
vreplace.c:  $(SP01)vreplace.c  
	cp $* $@
vsave.c:     $(SP01)vsave.c  
	cp $* $@
vsearch.c:   $(SP01)vsearch.c  
	cp $* $@
vexadb.c:    $(SP01)vexadb.c  
	cp $* $@
vexadb.h:    $(SP01)vexadb.h  
	cp $* $@
vdbok.c:    $(SP01)vdbok.c  
	cp $* $@
vwatch.c:    $(SP01)vwatch.c  
	cp $* $@
verror.c:    $(SP01)verror.c  
	cp $* $@
vshow.c:     $(SP01)vshow.c  
	cp $* $@
vtrad.c:     $(SP01)vtrad.c  
	cp $* $@
vwidget.c:   $(SP01)vwidget.c  
	cp $* $@
vcolours.c:  $(SP01)vcolours.c  
	cp $* $@
vstdfont.c:  $(SP01)vstdfont.c  
	cp $* $@
vsysfont.c:  $(SP01)vsysfont.c  
	cp $* $@
vcompare.c:  $(SP01)vcompare.c  
	cp $* $@
vilabel.c:  $(SP01)vilabel.c  
	cp $* $@
velabel.c:  $(SP01)velabel.c  
	cp $* $@
vvalid.c:  $(SP01)vvalid.c  
	cp $* $@
vcmpform.c: $(SP01)vcmpform.c
	cp $* $@
vrgb.c:     $(SP01)vrgb.c  
	cp $* $@
vnewpal.c: $(SP01)vnewpal.c  
	cp $* $@
vpaledit.c: $(SP01)vpaledit.c  
	cp $* $@

! make

# -------------------------------------
# transfer control to compilation phase
# -------------------------------------
vwall.c: $(SP01)vwall.c
	cp $* $@
vwall.h: $(SP01)vwall.h
	cp $* $@
vwbutton.c: $(SP01)vwbutton.c
	cp $* $@
vwbutton.h: $(SP01)vwbutton.h
	cp $* $@
vwcheck.c: $(SP01)vwcheck.c
	cp $* $@
vwcheck.h: $(SP01)vwcheck.h
	cp $* $@
vwdata.c: $(SP01)vwdata.c
	cp $* $@
vwdata.h: $(SP01)vwdata.h
	cp $* $@
vwedit.c: $(SP01)vwedit.c
	cp $* $@
vwedit.h: $(SP01)vwedit.h
	cp $* $@
vwfill.c: $(SP01)vwfill.c
	cp $* $@
vwfill.h: $(SP01)vwfill.h
	cp $* $@
vwform.c: $(SP01)vwform.c
	cp $* $@
vwform.h: $(SP01)vwform.h
	cp $* $@
vwframe.c: $(SP01)vwframe.c
	cp $* $@
vwframe.h: $(SP01)vwframe.h
	cp $* $@
vwgraph.c: $(SP01)vwgraph.c
	cp $* $@
vwgraph.h: $(SP01)vwgraph.h
	cp $* $@
vwidget.c: $(SP01)vwidget.c
	cp $* $@
vwimage.c: $(SP01)vwimage.c
	cp $* $@
vwimage.h: $(SP01)vwimage.h
	cp $* $@
vwline.c: $(SP01)vwline.c
	cp $* $@
vwline.h: $(SP01)vwline.h
	cp $* $@
vwprogress.c: $(SP01)vwprogress.c
	cp $* $@
vwprogress.h: $(SP01)vwprogress.h
	cp $* $@
vwradio.c: $(SP01)vwradio.c
	cp $* $@
vwradio.h: $(SP01)vwradio.h
	cp $* $@
vwscroll.c: $(SP01)vwscroll.c
	cp $* $@
vwscroll.h: $(SP01)vwscroll.h
	cp $* $@
vwselect.c: $(SP01)vwselect.c
	cp $* $@
vwselect.h: $(SP01)vwselect.h
	cp $* $@
vwswitch.c: $(SP01)vwswitch.c
	cp $* $@
vwswitch.h: $(SP01)vwswitch.h
	cp $* $@
vwtabpage.c: $(SP01)vwtabpage.c
	cp $* $@
vwtabpage.h: $(SP01)vwtabpage.h
	cp $* $@
vwtext.c: $(SP01)vwtext.c
	cp $* $@
vwtext.h: $(SP01)vwtext.h
	cp $* $@
vwwindow.c: $(SP01)vwwindow.c
	cp $* $@
vwwindow.h: $(SP01)vwwindow.h
	cp $* $@

! make

vtagdata.c: $(SP01)vtagdata.c
	cp $* $@

! make

cstyleman.c: $(SP01)cstyleman.c
	cp $* $@
! make

# ---------------------------------------------------
# extensions for the new database visual model editor
# ---------------------------------------------------
widgetmenu.c:  $(SP01)widgetmenu.c  
	cp $* $@
methodmenu.c:  $(SP01)methodmenu.c  
	cp $* $@
membermenu.c:  $(SP01)membermenu.c  
	cp $* $@
modelmenu.c:  $(SP01)modelmenu.c  
	cp $* $@
actormenu.c:  $(SP01)actormenu.c  
	cp $* $@
basemenu.c:  $(SP01)basemenu.c  
	cp $* $@
flowmenu.c:  $(SP01)flowmenu.c  
	cp $* $@
linkmenu.c:  $(SP01)linkmenu.c  
	cp $* $@
vxmlname.c:  $(SP01)vxmlname.c
	cp $* $@
vrelate.c:  $(SP01)vrelate.c
	cp $* $@
vbase.c:  $(SP01)vbase.c
	cp $* $@
vmodel.c:  $(SP01)vmodel.c
	cp $* $@
vreader.c:  $(SP01)vreader.c
	cp $* $@
! make
# ---------------------------------------
# Style Class Dependance Model Extensions
# ---------------------------------------
vdomain.c: $(SP01)vdomain.c
	cp $* $@
vdepmenu.c: $(SP01)vdepmenu.c
	cp $* $@
vdepmodmenu.c: $(SP01)vdepmodmenu.c
	cp $* $@
vmodmenu.c: $(SP01)vmodmenu.c
	cp $* $@
vsheet.c: $(SP01)vsheet.c
	cp $* $@

vformhelp.c: $(SP01)vformhelp.c
	cp $* $@

vcssname.c:  $(SP01)vcssname.c
	cp $* $@

vabalname.c:  $(SP01)vabalname.c
	cp $* $@

! make

! shell cd $(ABAL)/pixel; $(MAKE)


