/* File generated by /home/abal64/bin/linbda Version 2.1a.0.04 : /home/abal64/src/ned/editor.def -> /home/abal64/src/ned/editor.c */
#ifndef __linbda__home_abal64_src_ned_editor_c__
#define __linbda__home_abal64_src_ned_editor_c__
#include <stdio.h>
#include <setjmp.h>
#include "ldfbda.h"

private BDA * DynamicLibrary;
	public  LPBDA_INIT	rt_init;
	public  BDA_INIT	v_rt_init;
	public  BDA_ARG rt_arg;

/* ABAL Runtime Error Trap */
private	jmp_buf rt_error_context;
public  VOID rt_error(EXAWORD evalue) { 
	longjmp(rt_error_context,evalue);
	return;
}

private int function_counter=0;
/* ABAL Word Conversions */
public EXAWORD GetAbalInt8(char FAR PTR bptr)
{
	return(*bptr);
}

public EXAWORD GetAbalInt16(BYTE FAR PTR wptr)
{
	return(((*wptr<< 8)|*(wptr+1)));
}

public EXAWORD GetAbalInt32(BYTE FAR PTR wptr)
{
	int length=4;
	EXAWORD result=0;
	while ( length-- ) result = ((result << 8) | (*(wptr++) & 0x00FF));
	return(result);
}

public EXAWORD GetAbalInt64(BYTE FAR PTR wptr)
{
	int length=8;
	EXAWORD result=0;
	while ( length-- ) result = ((result << 8) | (*(wptr++) & 0x00FF));
	return(result);
}

public void PutAbalInt8(char FAR * wptr, EXAWORD v)
{
	*wptr = (v & 0x00FF);
	return;
}
public void PutAbalInt16(BYTE FAR * wptr, EXAWORD v)
{
	int length=2;
	while ( length-- ) { *(wptr +length) = (v & 0x00FF); v >>= 8; }
	return;
}

public void PutAbalInt32(BYTE FAR * wptr, EXAWORD v)
{
	int length=4;
	while ( length-- ) { *(wptr +length) = (v & 0x00FF); v >>= 8; }
	return;
}

public void PutAbalInt64(BYTE FAR * wptr, EXAWORD v)
{
	int length=8;
	while ( length-- ) { *(wptr +length) = (v & 0x00FF); v >>= 8; }
	return;
}

#define LdfParaWord(n) (tptr[n]==1 ? GetAbalInt16(pptr[n]) : (tptr[n]==0 ? GetAbalInt8(pptr[n]) : (tptr[n]==5 ? GetAbalInt32(pptr[n]): GetAbalInt64(pptr[n]) )))
#define LdfParaByte(n) (tptr[n]==1 ? (GetAbalInt16(pptr[n])&0x00FF) : (tptr[n]==0 ? GetAbalInt8(pptr[n]):(tptr[n]==5?(GetAbalInt32(pptr[n])&0x00FF):(GetAbalInt64(pptr[n])&0x00FF))))

private BYTE PTR function_names[256];
private char * trace_name=(char*)0;
private FILE * trace_handle=(FILE*)0;
extern long time(long*);

/* Trace Activation */
private void start_trace()
{
	trace_name = getenv("EDITOR_TRACE");
	if ( trace_name != (char *) 0 ) {
		trace_handle=fopen(trace_name,"w");
		}
	return;
}

/* Trace Write */
private void write_trace(char * mptr)
{
	if ( trace_handle != (FILE*)0) {
		fprintf(trace_handle,mptr);
		fprintf(trace_handle,"\r\n");
		}
	return;
}

/* Trace Result */
private void trace_result(EXAWORD result)
{
	if ( trace_handle != (FILE*)0) {
		fprintf(trace_handle,"RETURN: %u \r\n",result);
		}
	return;
}

/* Trace Call */
private void trace_call(
	EXAWORD fid,
	EXAWORD argc,
	BYTE FAR tptr[],
	VOID FAR PTR FAR pptr[],
	EXAWORD FAR wptr[])
{
	char * bptr;
	int	i=0;
	int	j=0;
	if ( trace_handle != (FILE*)0) {
			fprintf(trace_handle,"[%lu] ",time((long*)0));
		if ( function_names[fid] != (char *) 0) {
			fprintf(trace_handle,"(%s)",function_names[fid]);
			}
		else	{
			fprintf(trace_handle,"(call %u)",fid);
			}
		for (i=0; i < argc; i++) {
			switch(tptr[i]) {
				case 0x0080 : 
					fprintf(trace_handle,"\t(*b=%x)\r\n",*((bptr=pptr[i])));
					break;
				case 0  : 
					fprintf(trace_handle,"\t(b=%x)\r\n",*((bptr=pptr[i])));
					break;
				case 0x0081 : 
					fprintf(trace_handle,"\t(*w=%x)\r\n",GetAbalInt16(pptr[i]));
					break;
				case 1  : 
					fprintf(trace_handle,"\t(w=%x)\r\n",GetAbalInt16(pptr[i]));
					break;
				case 0x0085 : 
					fprintf(trace_handle,"\t(*w=%x)\r\n",GetAbalInt32(pptr[i]));
					break;
				case 5  : 
					fprintf(trace_handle,"\t(w=%x)\r\n",GetAbalInt32(pptr[i]));
					break;
				case 0x0086 : 
					fprintf(trace_handle,"\t(*w=%x)\r\n",GetAbalInt64(pptr[i]));
					break;
				case 6  : 
					fprintf(trace_handle,"\t(w=%x)\r\n",GetAbalInt64(pptr[i]));
					break;
				case 2  : 
				case 3  : 
				case 0x0082 : 
				case 0x0083 : 
					fprintf(trace_handle,"\t(*=");
					for (bptr=pptr[i],j=0;j<wptr[i];j++) {
						fprintf(trace_handle,"%x ",(*(bptr+j)&0x00FF));
						if ((j % 20) == 19) {
							fprintf(trace_handle,"\r\n");
							}
						}
					fprintf(trace_handle,")\r\n");
				};
			}
		fprintf(trace_handle,"\r\n");
		}
	return;
}

/* Trace Closure */
private void close_trace()
{
	if ( trace_handle != (FILE*)0) {
		fclose(trace_handle);
		trace_handle=(FILE*)0;
		}
	return;
}

/* Library Information */
public EXAWORD LdfBdaInformation(void * vptr)
{
	printf(
		"\n   Abal Dynamic Library : EDITOR64.Abal.3.3u.0.01"
		);
	printf(
		"\n   Copyright (c) Amenesik / Sologic \n\n"
		);
	return(0);
}

/* Library Destructor */
public EXAWORD LdfBdaTerminate()
{
	write_trace("LdfBdaTerminate()");
	close_trace();
	if (DynamicLibrary->fin != (VOID (FAR PTR)()) 0)
		 (*DynamicLibrary->fin)();
	return(0);
}

/* Library Call Through */
public EXAWORD LdfBdaExecute(
	EXAWORD fid,
	EXAWORD argc,
	BYTE FAR tptr[],
	VOID FAR PTR FAR pptr[],
	EXAWORD FAR wptr[],
	int FAR * eptr)
{
	EXAWORD	result=0;
	rt_arg.c=argc; rt_arg.v=pptr;
	rt_arg.l=wptr; rt_arg.t=tptr;
	if ((result=setjmp(rt_error_context))!=0) {
		if ( eptr != (int FAR *) 0) *eptr = result;
		return( result );
		}
	if ( trace_handle != (FILE*)0) {
	trace_call(fid,argc,tptr,pptr,wptr);
		}
	/* Version = 1 */
	/* Runtime = "editor" */
	switch ( fid ) {
		case	0 : /* % editorOnCreate($) */
			result=(*DynamicLibrary->fonction[0])(
				pptr[0]); break;
		case	1 : /* % editorOnRemove(%) */
			result=(*DynamicLibrary->fonction[1])(
				LdfParaWord(0)); break;
		case	2 : /* % editorOnShow(%) */
			result=(*DynamicLibrary->fonction[2])(
				LdfParaWord(0)); break;
		case	3 : /* % editorOnHide(%) */
			result=(*DynamicLibrary->fonction[3])(
				LdfParaWord(0)); break;
		case	4 : /* % editorOnGetFocus(%) */
			result=(*DynamicLibrary->fonction[4])(
				LdfParaWord(0)); break;
		case	5 : /* % editorOnLoseFocus(%) */
			result=(*DynamicLibrary->fonction[5])(
				LdfParaWord(0)); break;
		case	6 : /* % editorOnUseEvent(%) */
			result=(*DynamicLibrary->fonction[6])(
				LdfParaWord(0)); break;
		case	7 : /* % editorOnExec(%) */
			result=(*DynamicLibrary->fonction[7])(
				LdfParaWord(0)); break;
		default	: result=138;
		break;
		}
	/* End */
	if ( trace_handle != (FILE*)0) {
		trace_result( result );
	trace_call(fid,argc,tptr,pptr,wptr);
		}
	return(result);
}

/* Library Constructor */

public EXAWORD LdfBdaInitialise(
	BDA_INIT FAR PTR descriptor,
	EXAWORD dlength)
{
	int	i=0;
	rt_init = descriptor;
	function_counter=8;
	function_names[0] = "% editorOnCreate($)";
	function_names[1] = "% editorOnRemove(%)";
	function_names[2] = "% editorOnShow(%)";
	function_names[3] = "% editorOnHide(%)";
	function_names[4] = "% editorOnGetFocus(%)";
	function_names[5] = "% editorOnLoseFocus(%)";
	function_names[6] = "% editorOnUseEvent(%)";
	function_names[7] = "% editorOnExec(%)";
	start_trace();
	write_trace("LdfBdaInitialise()");
	if (!(DynamicLibrary = InitRelais()))
		return(139);
	else	return(0);
}

#endif  /* __linbda__home_abal64_src_ned_editor_c__ */
/* End of File */
