! ifdef old_project
T    = $(ABAL)/src/sing/
COPY = cp 

$(T)vcompare.c:   vcompare.c
	$(COPY) $* $@
$(T)vamake.c:   vamake.c
	$(COPY) $* $@
$(T)vana.c:   vana.c
	$(COPY) $* $@
$(T)vyna.c:   vyna.c
	$(COPY) $* $@
$(T)vabout.c:   vabout.c
	$(COPY) $* $@
$(T)vnation.c:   vnation.c
	$(COPY) $* $@
$(T)vhelper.c:   vhelper.c
	$(COPY) $* $@
$(T)vcompose.c:   vcompose.c
	$(COPY) $* $@
$(T)vaccess.c:  vaccess.c
	$(COPY) $* $@
$(T)vaed.c:     vaed.c
	$(COPY) $* $@
$(T)vaprod.c:   vaprod.c
	$(COPY) $* $@
$(T)vcamera.c: vcamera.c
	$(COPY) $* $@
$(T)vclass.c: vclass.c
	$(COPY) $* $@
$(T)vconfig.c: vconfig.c
	$(COPY) $* $@
$(T)vconst.c: vconst.c
	$(COPY) $* $@
$(T)vcprod.c: vcprod.c
	$(COPY) $* $@
$(T)vcube.c: vcube.c
	$(COPY) $* $@
$(T)vdata.c: vdata.c
	$(COPY) $* $@
$(T)vdebug.c: vdebug.c
	$(COPY) $* $@
$(T)vedcmd.c: vedcmd.c
	$(COPY) $* $@
$(T)veditor.c: veditor.c
	$(COPY) $* $@
$(T)verror.c: verror.c
	$(COPY) $* $@
$(T)vexadb.c: vexadb.c
	$(COPY) $* $@
$(T)vexit.c: vexit.c
	$(COPY) $* $@
$(T)vfextr.c: vfextr.c
	$(COPY) $* $@
$(T)vfile.c: vfile.c
	$(COPY) $* $@
$(T)vfload.c: vfload.c
	$(COPY) $* $@
$(T)vform.c: vform.c
	$(COPY) $* $@
$(T)vfsave.c: vfsave.c
	$(COPY) $* $@
$(T)vfselect.c: vfselect.c
	$(COPY) $* $@
$(T)vheader.c: vheader.c
	$(COPY) $* $@
$(T)vhtml.c: vhtml.c
	$(COPY) $* $@
$(T)viload.c: viload.c
	$(COPY) $* $@
$(T)vimage.c: vimage.c
	$(COPY) $* $@
$(T)vimport.c: vimport.c
	$(COPY) $* $@
$(T)vintro.c: vintro.c
	$(COPY) $* $@
$(T)visave.c: visave.c
	$(COPY) $* $@
$(T)vlink.c: vlink.c
	$(COPY) $* $@
$(T)vload.c: vload.c
	$(COPY) $* $@
$(T)vmenu.c: vmenu.c
	$(COPY) $* $@
$(T)vmethod.c: vmethod.c
	$(COPY) $* $@
$(T)vmload.c: vmload.c
	$(COPY) $* $@
$(T)vmprod.c: vmprod.c
	$(COPY) $* $@
$(T)vmsave.c: vmsave.c
	$(COPY) $* $@
$(T)voption.c: voption.c
	$(COPY) $* $@
$(T)vpage.c: vpage.c
	$(COPY) $* $@
$(T)vparam.c: vparam.c
	$(COPY) $* $@
$(T)vpragma.c: vpragma.c
	$(COPY) $* $@
$(T)vrecrep.c: vrecrep.c
	$(COPY) $* $@
$(T)vrefer.c: vrefer.c
	$(COPY) $* $@
$(T)vreplace.c: vreplace.c
	$(COPY) $* $@
$(T)vsave.c: vsave.c
	$(COPY) $* $@
$(T)vsearch.c: vsearch.c
	$(COPY) $* $@
$(T)vtexport.c: vtexport.c
	$(COPY) $* $@
$(T)vtimport.c: vtimport.c
	$(COPY) $* $@
$(T)vtrad.c: vtrad.c
	$(COPY) $* $@
$(T)vwidget.c: vwidget.c
	$(COPY) $* $@

! make

$(T)editmenu.c: editmenu.c
	$(COPY) $* $@
$(T)evenmenu.c: evenmenu.c
	$(COPY) $* $@
$(T)filemenu.c: filemenu.c
	$(COPY) $* $@
$(T)formmenu.c: formmenu.c
	$(COPY) $* $@
$(T)imagmenu.c: imagmenu.c
	$(COPY) $* $@
#$(T)mainmenu.c: mainmenu.c
#	$(COPY) $* $@
$(T)optimenu.c: optimenu.c
	$(COPY) $* $@
$(T)projmenu.c: projmenu.c
	$(COPY) $* $@
$(T)tracmenu.c: tracmenu.c
	$(COPY) $* $@
$(T)viewmenu.c: viewmenu.c
	$(COPY) $* $@
$(T)widgmenu.c: widgmenu.c
	$(COPY) $* $@


! endif

! shell cd $(ABAL)/ao;   $(MAKE)
! shell cd $(ABAL)/ned;   $(MAKE)
! shell cd $(ABAL)/pixel; $(MAKE)
! shell cd $(ABAL)/exa;   $(MAKE)

