#ifndef	_singpars_c
#define	_singpars_c

#define	MAX_VISUAL_MEMBER	0x0029

#define	VISUAL_MEMBER_X			0x0000
#define	VISUAL_MEMBER_Y			0x0001
#define	VISUAL_MEMBER_W			0x0002
#define	VISUAL_MEMBER_H			0x0003
#define	VISUAL_MEMBER_FONT		0x0004
#define	VISUAL_MEMBER_FG		0x0005
#define	VISUAL_MEMBER_BG		0x0006
#define	VISUAL_MEMBER_VALUE		0x0007
#define	VISUAL_MEMBER_BUFFER		0x0008
#define	VISUAL_MEMBER_LIMIT		0x0009
#define	VISUAL_MEMBER_MAX		0x000A
#define	VISUAL_MEMBER_LINE		0x000B
#define	VISUAL_MEMBER_LINES		0x000C
#define	VISUAL_MEMBER_LINESIZE		0x000D
#define	VISUAL_MEMBER_FONTWIDTH		0x000E
#define	VISUAL_MEMBER_FONTHEIGHT	0x000F
#define	VISUAL_MEMBER_COLUMN    	0x0010
#define	VISUAL_MEMBER_COLUMNS    	0x0011
#define	VISUAL_MEMBER_SIZE       	0x0012
#define	VISUAL_MEMBER_COLUMNSIZE       	0x0013
#define	VISUAL_MEMBER_POSITION         	0x0014
#define	VISUAL_MEMBER_PAYLOAD		0x0015
#define	VISUAL_MEMBER_FORMAT		0x0016

#define	MAX_VISUAL_PROPERTY		0x0016

#define	VISUAL_MEMBER_CREATE		MAX_VISUAL_PROPERTY+0x0001
#define	VISUAL_MEMBER_SHOW		MAX_VISUAL_PROPERTY+0x0002
#define	VISUAL_MEMBER_GETFOCUS		MAX_VISUAL_PROPERTY+0x0003
#define	VISUAL_MEMBER_EVENT		MAX_VISUAL_PROPERTY+0x0004
#define	VISUAL_MEMBER_LOSEFOCUS		MAX_VISUAL_PROPERTY+0x0005
#define	VISUAL_MEMBER_HIDE		MAX_VISUAL_PROPERTY+0x0006
#define	VISUAL_MEMBER_REMOVE		MAX_VISUAL_PROPERTY+0x0007
#define	VISUAL_MEMBER_ONSHOW		MAX_VISUAL_PROPERTY+0x0008
#define	VISUAL_MEMBER_ONHIDE		MAX_VISUAL_PROPERTY+0x0009
#define	VISUAL_MEMBER_ONFOCUS 		MAX_VISUAL_PROPERTY+0x000A
#define	VISUAL_MEMBER_TRIGGER		MAX_VISUAL_PROPERTY+0x000B
#define	VISUAL_MEMBER_FREEZE		MAX_VISUAL_PROPERTY+0x000C
#define	VISUAL_MEMBER_THAW  		MAX_VISUAL_PROPERTY+0x000D
#define	VISUAL_MEMBER_FILL  		MAX_VISUAL_PROPERTY+0x000E
#define	VISUAL_MEMBER_WIPE  		MAX_VISUAL_PROPERTY+0x000F
#define	VISUAL_MEMBER_RESET 		MAX_VISUAL_PROPERTY+0x0010
#define	VISUAL_MEMBER_VIEWPORT 		MAX_VISUAL_PROPERTY+0x0011
#define	VISUAL_MEMBER_KEY 		MAX_VISUAL_PROPERTY+0x0012

#define	DATA_MEMBER_ASSIGN		0
#define	DATA_MEMBER_OPEN		1
#define	DATA_MEMBER_CLOSE		2
#define	DATA_MEMBER_CFILE		3
#define	DATA_MEMBER_DFILE		4
#define	DATA_MEMBER_UPDATE		5
#define	DATA_MEMBER_INSERT		6
#define	DATA_MEMBER_MODIF		7
#define	DATA_MEMBER_DELETE		8
#define	DATA_MEMBER_SEARCH		9
#define	DATA_MEMBER_FIRST		10
#define	DATA_MEMBER_UP			11
#define	DATA_MEMBER_PREVIOUS		12
#define	DATA_MEMBER_DOWN		13
#define	DATA_MEMBER_NEXT		14
#define	DATA_MEMBER_LAST		15
#define	DATA_MEMBER_INDEX		16
#define	DATA_MEMBER_ERROR		17
#define	DATA_MEMBER_HANDLE		18
#define	DATA_MEMBER_LOCK		19
#define	DATA_MEMBER_POSIT		20
#define	DATA_MEMBER_COUNT		21
#define	DATA_MEMBER_QUESTION		22
#define	DATA_MEMBER_RESPONSE		23
#define	DATA_MEMBER_LENGTH		24
#define	DATA_MEMBER_COLLECT		25
#define	DATA_MEMBER_LOCATE		26
#define	MAX_DATA_MEMBER			27

struct	line_parser	{
	int		status;
	char	*	thisname;
	struct line_parser * nesting;
	char	*	string;
	int		offset;
	int		tokenlen;
	char		token[320];
	};

#endif	/*_singpars_c */


