#ifndef	_singx3d_h
#define	_singx3d_h

/*	------------------------------------------------------------------------------------------	*/
/* 	Document Type Definition or Declaration for Visual Forms Ressource Files generated by Sing 	*/
/*	------------------------------------------------------------------------------------------	*/

static	char *	XmlElement[] = {
	(char *) "THREED",
	(char *) "NAME",
	(char *) "VECTOR",
	(char *) "SIZES",
	(char *) "POSITION",
	(char *) "FOCUS",
	(char *) "DIRECTION",
	(char *) "MOVEMENT",
	(char *) "TIMER",
	(char *) "STEP",
	(char *) "OPTION",
	(char *) "IMAGE",
	(char *) "FILL",
	(char *) "DOCUMENT",
	(char *) "DOCNAME",
	(char *) "OBJECT",
	(char *) "TOPLEFT",
	(char *) "BOTTOMRIGHT",
	(char *) "NATURE",
	(char *) "XLR",
	(char *) "YUL",
	(char *) "ZFB",
	(char *) "SHL",
	(char *) "FORM",
	(char *) "TEXT",
	(char *) "PRODUCTION",
	(char *) "TARGET",
	(char *) "LANGUAGE",
	(char *) "PROJECT",
	(char *) "MAKEFILE",
	(char *) "CONFIGURE",
	(char *) "HTML-PRODUCTION",
	(char *) "TITLE",
	(char *) "SCREEN",
	(char *) "PRINT",
	(char *) "LOGO",
	(char *) "FOOTER",
	(char *) "PATH",
	(char *) "SEPARATE",
	(char *) "REPORT",
	(char *) "NATIONAL",

	/* Tags for database file description management */
	/* --------------------------------------------- */
	(char *) "SQFILE",
	(char *) "SIFILE",
	(char *) "MCFILE",
	(char *) "DBFILE",
	(char *) "VMEMORY",
	(char *) "INDEX",
	(char *) "RECORD",
	(char *) "CLASS",
	(char *) "SIZE",
	(char *) "MEMBER",
	(char *) "FILE",
	(char *) "TYPE",
	(char *) "DATABASE",
	(char *) "BASE",
	(char *) "ICONS",
	(char *) "PALETTE",

	/* Tags for the TreeViewer Configuration */
	/* ------------------------------------- */
	(char *) "TREEVIEW",
	(char *) "FONT",
	(char *) "ZONE",
	(char *) "SPACING",
	(char *) "SOURCE",
	(char *) "PACKAGE",
	(char *) "IDENTITY",
	(char *) "WIDTH"    

	};

#define	ELEMENT_THREED		0x0000
#define	ELEMENT_NAME		0x0001
#define	ELEMENT_VECTOR		0x0002
#define	ELEMENT_SIZES		0x0003
#define	ELEMENT_POSITION	0x0004
#define	ELEMENT_FOCUS		0x0005
#define	ELEMENT_DIRECTION	0x0006
#define	ELEMENT_MOVEMENT	0x0007
#define	ELEMENT_TIMER		0x0008
#define	ELEMENT_STEP		0x0009
#define	ELEMENT_OPTION		0x000A
#define	ELEMENT_IMAGE		0x000B
#define	ELEMENT_FILL		0x000C
#define	ELEMENT_DOCUMENT	0x000D
#define	ELEMENT_DOCNAME 	0x000E
#define	ELEMENT_OBJECT		0x000F
#define	ELEMENT_TOPLEFT		0x0010
#define	ELEMENT_BOTTOMRIGHT	0x0011
#define	ELEMENT_NATURE		0x0012
#define	ELEMENT_XLR		0x0013
#define	ELEMENT_YUL		0x0014
#define	ELEMENT_ZFB		0x0015
#define	ELEMENT_SHL		0x0016
#define	ELEMENT_FORM		0x0017
#define	ELEMENT_TEXT		0x0018
#define ELEMENT_PRODUCTION	0x0019
#define ELEMENT_TARGET		0x001A
#define ELEMENT_LANGUAGE	0x001B
#define ELEMENT_PROJECT		0x001C
#define ELEMENT_MAKEFILE	0x001D
#define ELEMENT_CONFIGURE	0x001E
#define ELEMENT_HTML_PRODUCTION	0x001F
#define ELEMENT_TITLE		0x0020
#define ELEMENT_SCREEN		0x0021
#define ELEMENT_PRINT		0x0022
#define ELEMENT_LOGO		0x0023
#define ELEMENT_FOOTER		0x0024
#define ELEMENT_PATH		0x0025
#define ELEMENT_SEPARATE	0x0026
#define ELEMENT_REPORT		0x0027
#define ELEMENT_NATIONAL	0x0028
#define	DATABASE_SQFILE		0x0029		
#define	DATABASE_SIFILE		0x002A		
#define	DATABASE_MCFILE		0X002B
#define	DATABASE_DBFILE		0x002C		
#define	DATABASE_VMEMORY	0x002D
#define	DATABASE_INDEX		0x002E
#define	DATABASE_RECORD		0x002F
#define	DATABASE_CLASS		0x0030
#define	DATABASE_SIZE		0x0031
#define	DATABASE_MEMBER		0x0032
#define	DATABASE_FILE		0x0033
#define	DATABASE_TYPE		0x0034
#define ELEMENT_DATABASE	0x0035
#define ELEMENT_BASE		0x0036
#define ELEMENT_ICONS		0x0037
#define ELEMENT_PALETTE 	0x0038
#define ELEMENT_TREEVIEW	0x0039
#define ELEMENT_FONT		0x003A
#define ELEMENT_ZONE		0x003B
#define ELEMENT_SPACING		0x003C
#define ELEMENT_SOURCE		0x003D
#define ELEMENT_PACKAGE		0x003E
#define ELEMENT_IDENTITY	0x003F
#define ELEMENT_WIDTH   	0x0040
#define	MAX_ELEMENT		0x0041

#endif	/* _singx3d_h */
	/* ---------- */


