#ifndef	_SINGEDIT_H
#define	_SINGEDIT_H


#define	MAX_EDITOR_BUFFER	1608
#define	EDIT_FONT_WIDTH		 8
#define	EDIT_FONT_HEIGHT	16
#define	EDITOR_WIDTH		540
#define	EDITOR_COLUMNS		EDITOR_WIDTH / EDIT_FONT_WIDTH
#define	EDITOR_ROWS		MAX_EDITOR_BUFFER/EDITOR_COLUMNS



#endif	/* _SINGEDIT_H	*/


