#ifndef	_singpars_c
#define	_singpars_c

#define	VISUAL_MEMBER_X			0x0000
#define	VISUAL_MEMBER_Y			0x0001
#define	VISUAL_MEMBER_W			0x0002
#define	VISUAL_MEMBER_H			0x0003
#define	VISUAL_MEMBER_FONT		0x0004
#define	VISUAL_MEMBER_FG		0x0005
#define	VISUAL_MEMBER_BG		0x0006
#define	VISUAL_MEMBER_VALUE		0x0007
#define	VISUAL_MEMBER_BUFFER		0x0008
#define	VISUAL_MEMBER_LIMIT		0x0009
#define	VISUAL_MEMBER_MAX		0x000A
#define	VISUAL_MEMBER_LINE		0x000B
#define	VISUAL_MEMBER_LINES		0x000C
#define	VISUAL_MEMBER_LINESIZE		0x000D
#define	VISUAL_MEMBER_FONTWIDTH		0x000E
#define	VISUAL_MEMBER_FONTHEIGHT	0x000F
#define	VISUAL_MEMBER_COLUMN    	0x0010
#define	VISUAL_MEMBER_COLUMNS    	0x0011
#define	VISUAL_MEMBER_SIZE       	0x0012
#define	VISUAL_MEMBER_COLUMNSIZE       	0x0013
#define	VISUAL_MEMBER_POSITION         	0x0014
#define	VISUAL_MEMBER_PAYLOAD		0x0015
#define	VISUAL_MEMBER_FORMAT		0x0016
#define	VISUAL_MEMBER_HOTKEY		0x0017
#define	VISUAL_MEMBER_FOCUS 		0x0018
#define	VISUAL_MEMBER_PAGE  		0x0019
#define	VISUAL_MEMBER_STYLE  		0x001A
#define	VISUAL_MEMBER_HINT		0x001B
#define VISUAL_MEMBER_FORMSORT		0x001C
#define VISUAL_MEMBER_TABSORT		0x001D
#define VISUAL_MEMBER_LINESORT		0x001E
#define VISUAL_MEMBER_START_SORT	0x001F
#define VISUAL_MEMBER_SORT		0x0020
#define	VISUAL_MEMBER_OFFSET		0x0021
#define	VISUAL_MEMBER_ATTACH		0x0022
#define	VISUAL_MEMBER_DETACH		0x0023
#define	VISUAL_MEMBER_HELP		0x0024
#define	VISUAL_MEMBER_ACCESS		0x0025
#define	VISUAL_MEMBER_ENABLE		0x0026
#define	VISUAL_MEMBER_DISABLE		0x0027
#define	VISUAL_MEMBER_INIBIT		0x0028
#define	VISUAL_MEMBER_HOTKEYS		0x0029
#define	MAX_VISUAL_PROPERTY		0x0029

#define	VISUAL_MEMBER_CREATE		MAX_VISUAL_PROPERTY+0x0001
#define	VISUAL_MEMBER_SHOW		MAX_VISUAL_PROPERTY+0x0002
#define	VISUAL_MEMBER_GETFOCUS		MAX_VISUAL_PROPERTY+0x0003
#define	VISUAL_MEMBER_EVENT		MAX_VISUAL_PROPERTY+0x0004
#define	VISUAL_MEMBER_LOSEFOCUS		MAX_VISUAL_PROPERTY+0x0005
#define	VISUAL_MEMBER_HIDE		MAX_VISUAL_PROPERTY+0x0006
#define	VISUAL_MEMBER_REMOVE		MAX_VISUAL_PROPERTY+0x0007
#define	VISUAL_MEMBER_ONSHOW		MAX_VISUAL_PROPERTY+0x0008
#define	VISUAL_MEMBER_ONHIDE		MAX_VISUAL_PROPERTY+0x0009
#define	VISUAL_MEMBER_ONFOCUS 		MAX_VISUAL_PROPERTY+0x000A
#define	VISUAL_MEMBER_TRIGGER		MAX_VISUAL_PROPERTY+0x000B
#define	VISUAL_MEMBER_FREEZE		MAX_VISUAL_PROPERTY+0x000C
#define	VISUAL_MEMBER_THAW  		MAX_VISUAL_PROPERTY+0x000D
#define	VISUAL_MEMBER_FILL  		MAX_VISUAL_PROPERTY+0x000E
#define	VISUAL_MEMBER_WIPE  		MAX_VISUAL_PROPERTY+0x000F
#define	VISUAL_MEMBER_RESET 		MAX_VISUAL_PROPERTY+0x0010
#define	VISUAL_MEMBER_VIEWPORT 		MAX_VISUAL_PROPERTY+0x0011
#define	VISUAL_MEMBER_KEY 		MAX_VISUAL_PROPERTY+0x0012
#define	VISUAL_MEMBER_PRESS		MAX_VISUAL_PROPERTY+0x0013
#define	VISUAL_MEMBER_ONCREATE 		MAX_VISUAL_PROPERTY+0x0014
#define	VISUAL_MEMBER_ONREMOVE 		MAX_VISUAL_PROPERTY+0x0015
#define	VISUAL_MEMBER_ONSET    		MAX_VISUAL_PROPERTY+0x0016
#define	VISUAL_MEMBER_ONGET    		MAX_VISUAL_PROPERTY+0x0017
#define	VISUAL_MEMBER_ONEVENT  		MAX_VISUAL_PROPERTY+0x0018
#define	VISUAL_MEMBER_DROP  		MAX_VISUAL_PROPERTY+0x0019
#define	VISUAL_MEMBER_ALLOCATE		MAX_VISUAL_PROPERTY+0x001A
#define	VISUAL_MEMBER_GET   		MAX_VISUAL_PROPERTY+0x001B
#define	VISUAL_MEMBER_PUT   		MAX_VISUAL_PROPERTY+0x001C
#define	VISUAL_MEMBER_ACTION		MAX_VISUAL_PROPERTY+0x001D

#define	MAX_VISUAL_MEMBER		MAX_VISUAL_PROPERTY+0x001E

#define	DATA_MEMBER_ASSIGN		0
#define	DATA_MEMBER_OPEN		1
#define	DATA_MEMBER_CLOSE		2
#define	DATA_MEMBER_CFILE		3
#define	DATA_MEMBER_DFILE		4
#define	DATA_MEMBER_UPDATE		5
#define	DATA_MEMBER_INSERT		6
#define	DATA_MEMBER_MODIF		7
#define	DATA_MEMBER_DELETE		8
#define	DATA_MEMBER_SEARCH		9
#define	DATA_MEMBER_FIRST		10
#define	DATA_MEMBER_UP			11
#define	DATA_MEMBER_PREVIOUS		12
#define	DATA_MEMBER_DOWN		13
#define	DATA_MEMBER_NEXT		14
#define	DATA_MEMBER_LAST		15
#define	DATA_MEMBER_INDEX		16
#define	DATA_MEMBER_ERROR		17
#define	DATA_MEMBER_HANDLE		18
#define	DATA_MEMBER_LOCK		19
#define	DATA_MEMBER_POSIT		20
#define	DATA_MEMBER_COUNT		21
#define	DATA_MEMBER_QUESTION		22
#define	DATA_MEMBER_RESPONSE		23
#define	DATA_MEMBER_LENGTH		24
#define	DATA_MEMBER_COLLECT		25
#define	DATA_MEMBER_LOCATE		26
#define	DATA_MEMBER_LINK 		27
#define	DATA_MEMBER_CLINK 		28
#define	DATA_MEMBER_ONCREATE 		29
#define	DATA_MEMBER_ONREMOVE 		30
#define	DATA_MEMBER_RENAME 		31
#define	DATA_MEMBER_ATB 		32
#define	DATA_MEMBER_MARKER 		33
#define	DATA_MEMBER_KEY 		34
#define	DATA_MEMBER_FKEY 		35
#define	DATA_MEMBER_CKEY 		36
#define	DATA_MEMBER_RKEY 		37
#define	DATA_MEMBER_NKEY 		38
#define	DATA_MEMBER_FLAG 		39

#define	DATA_MEMBER_RECORD 		40
#define	DATA_MEMBER_JOIN 		41
#define	DATA_MEMBER_CJOIN 		42
#define	DATA_MEMBER_DJOIN 		43
#define	DATA_MEMBER_RJOIN 		44
#define	DATA_MEMBER_LJOIN 		45
#define	DATA_MEMBER_LFILE 		46
#define	DATA_MEMBER_LLIST 		47
#define	DATA_MEMBER_LKEY 		48

#define	DATA_MEMBER_DIRECTION		49

#define	MAX_DATA_MEMBER			50

struct	line_parser	{
	int		status;
	char	*	thisname;
	struct line_parser * nesting;
	char	*	string;
	int		offset;
	int		tokenlen;
	char		token[320];
	};

#endif	/*_singpars_c */


