#define	_VISUAL_VERSION		 0
#define	_VISUAL_CONFIG		 1
#define	_VISUAL_RECORD		 2
#define	_VISUAL_REPLAY		 3
#define	_VISUAL_FONTWIDTH  	 4
#define	_VISUAL_FONTHEIGHT 	 5
#define	_VISUAL_TRACE		 6
#define	_VISUAL_TITLE		 7
#define	_VISUAL_ICON 		 8
#define	_VISUAL_HELP 		 9
#define	_VISUAL_HOTKEY		10
#define	_VISUAL_LANGUAGE	11
#define	_VISUAL_TRIGGER		12

#define	_VISUAL_PUSHVIEWPORT	13
#define	_VISUAL_POPVIEWPORT	14

#define	_VISUAL_BUFFERWIDTH	15
#define	_VISUAL_BUFFERHEIGHT	16

#define	_VISUAL_IMAGENAME	17
#define	_VISUAL_IMAGEWIDTH	18
#define	_VISUAL_IMAGEHEIGHT	19

#define	_VISUAL_ATRIBUT		20
#define	_VISUAL_ECHO		21
#define	_VISUAL_SAVEGIF		22
#define	_VISUAL_SAVEBMP		23

#define	_VISUAL_IMAGECOUNT	24
#define	_VISUAL_DROPIMAGE	25

#define	_VISUAL_TEXTLENGTH	26
#define	_VISUAL_FONTNAME	27
#define	_VISUAL_IMAGEINFO	28

#define	_VISUAL_PAGEVIEWPORT	29

#define	_VISUAL_STYLE		30
#define	_VISUAL_DROPSTYLE	31
#define	_VISUAL_SAVEJPG		32
#define	_VISUAL_SAVEPNG		33

#define	_VISUAL_DOMAIN		35
#define	_VISUAL_CLASS		36
#define	_VISUAL_STYLEHEIGHT	37
#define	_VISUAL_STYLEWIDTH	38
#define	_VISUAL_STYLEFONT	39

#define	_VISUAL_CONVISO		40
#define	_VISUAL_CONVPRL		41

#define	_VISUAL_GETKEYS		42
#define	_VISUAL_SETKEYS		43
#define _VISUAL_GETCLIP		44
#define _VISUAL_SETCLIP		45
#define _VISUAL_GETCLIP_NOCONV	46
#define _VISUAL_SETCLIP_NOCONV	47
#define	_VISUAL_GETEDIT		48
#define	_VISUAL_SETEDIT		49

#define	_VISUAL_STATUS		50
#define	_VISUAL_DEFAULT		51

#define  _VISUAL_PRN_BUFFER	70 /* FCH PROVISOIRE (test)!!! */
#define  _VISUAL_PLAYSOUND	99 /* FCH PROVISOIRE (test)!!! */




