
#ifndef _vexadb_h
#define _vexadb_h
/* ------------------------------------------------------------------------- */
/* Warning : this file has been generated and should not be modified by hand */
/* ------------------------------------------------------------------------- */
/* Sing Version   : 2.1a.0.32                                                */
/* Production     : C                                                        */
/* Project        : vexadb.xml                                               */
/* Target         : vexadb.h                                                 */
/* Identification : 0.0-1184084574-7596.7595                                 */
/* ------------------------------------------------------------------------- */


private struct visual_debug_context {
	int	status;
	int	keycode;
	int	focus_item;
	int	focus_items;
	int	window_col;
	int	window_row;
	int	language;
	int	focus_pages[4+1];
	char * msg_Main[8];
	char * hint_Main[8];
	int	x_Main;
	int	y_Main;
	int	w_Main;
	int	h_Main;
	char * msg_ProgramSource[8];
	int	trigger_ProgramSource;
	char * hint_ProgramSource[8];
	int	page_number;
	char * msg_Auto2888[8];
	char * hint_Auto2888[8];
	char * hint_Auto2889[8];
	char * msg_Auto2890[8];
	char * hint_Auto2890[8];
	char * hint_Auto2891[8];
	char * msg_BreakManager[8];
	char * hint_BreakManager[8];
	char * hint_BreakFrame[8];
	char * msg_BreakPoint[8];
	char * hint_BreakPoint[8];
	int	x_BreakPoint;
	int	y_BreakPoint;
	int	w_BreakPoint;
	int	h_BreakPoint;
	int	fg_BreakPoint;
	int	bg_BreakPoint;
	int	fid_BreakPoint;
	char * msg_StepInto[8];
	char * hint_StepInto[8];
	char * msg_Goto[8];
	char * hint_Goto[8];
	char * msg_Run[8];
	char * hint_Run[8];
	char * msg_Restart[8];
	char * hint_Restart[8];
	char * msg_Break[8];
	char * hint_Break[8];
	char * msg_ClearBreak[8];
	char * hint_ClearBreak[8];
	char * msg_View[8];
	char * hint_View[8];
	char * msg_Help[8];
	char * hint_Help[8];
	char * msg_Save[8];
	char * hint_Save[8];
	char * msg_Exit[8];
	char * hint_Exit[8];
	char * msg_BreakKey[8];
	int	trigger_BreakKey;
	char * hint_BreakKey[8];
	int	value_BreakKey;
	char * msg_AsmList[8];
	int	trigger_AsmList;
	char * hint_AsmList[8];
	int	value_AsmList;
	char * msg_SaveConfig[8];
	int	trigger_SaveConfig;
	char * hint_SaveConfig[8];
	int	value_SaveConfig;
	char * msg_HexaView[8];
	int	trigger_HexaView;
	char * hint_HexaView[8];
	int	value_HexaView;
	char * hint_Dbio[8];
	char	buffer_Dbio[4033];
	char * msg_BreakBar[8];
	char * hint_BreakBar[8];
	int	x_BreakBar;
	int	y_BreakBar;
	int	w_BreakBar;
	int	h_BreakBar;
	int	fg_BreakBar;
	int	bg_BreakBar;
	int	fid_BreakBar;
	char * msg_DebugCursor[8];
	char * hint_DebugCursor[8];
	int	x_DebugCursor;
	int	y_DebugCursor;
	int	w_DebugCursor;
	int	h_DebugCursor;
	int	fg_DebugCursor;
	int	bg_DebugCursor;
	int	fid_DebugCursor;
	char * msg_ProgramOutput[8];
	int	trigger_ProgramOutput;
	char * hint_ProgramOutput[8];
	char * msg_Auto2892[8];
	char * hint_Auto2892[8];
	char * hint_Prio[8];
	char	buffer_Prio[4026];
	char * hint_VSB[8];
	int	value_VSB;
	int	limit_VSB;
	int	max_VSB;
	char * hint_HSB[8];
	int	value_HSB;
	int	limit_HSB;
	int	max_HSB;
	char * msg_DebugControl[8];
	int	trigger_DebugControl;
	char * hint_DebugControl[8];
	char * msg_Auto2893[8];
	char * hint_Auto2893[8];
	char * hint_Auto2894[8];
	char * hint_ErrAdr[8];
	char	buffer_ErrAdr[12];
	char * hint_AskMask[8];
	char	buffer_AskMask[12];
	char * hint_MouseMask[8];
	char	buffer_MouseMask[12];
	char * hint_ErrorAdr[8];
	char	buffer_ErrorAdr[12];
	char * hint_ErrorVal[8];
	char	buffer_ErrorVal[9];
	char * msg_Auto2895[8];
	char * hint_Auto2895[8];
	char * msg_Auto2896[8];
	char * hint_Auto2896[8];
	char * msg_Auto2897[8];
	char * hint_Auto2897[8];
	char * msg_Auto2898[8];
	char * hint_Auto2898[8];
	char * msg_Auto2899[8];
	char * hint_Auto2899[8];
	char * msg_Auto2900[8];
	char * hint_Auto2900[8];
	char * msg_Auto2901[8];
	char * hint_Auto2901[8];
	char * msg_Auto2902[8];
	char * hint_Auto2902[8];
	char * msg_Auto2903[8];
	char * hint_Auto2903[8];
	char * msg_Auto2904[8];
	char * hint_Auto2904[8];
	char * msg_Auto2905[8];
	char * hint_Auto2905[8];
	char * msg_Auto2906[8];
	char * hint_Auto2906[8];
	char * msg_Auto2907[8];
	char * hint_Auto2907[8];
	char * msg_Auto2908[8];
	char * hint_Auto2908[8];
	char * msg_Auto2909[8];
	char * hint_Auto2909[8];
	char * msg_Auto2910[8];
	char * hint_Auto2910[8];
	char * msg_Auto2911[8];
	char * hint_Auto2911[8];
	char * msg_Auto2912[8];
	char * hint_Auto2912[8];
	char * msg_Auto2913[8];
	char * hint_Auto2913[8];
	char * msg_Auto2914[8];
	char * hint_Auto2914[8];
	char * msg_Auto2915[8];
	char * hint_Auto2915[8];
	char * msg_ProcName[8];
	char * hint_ProcName[8];
	int	value_ProcName;
	char * msg_ProcEdit[8];
	int	trigger_ProcEdit;
	char * hint_ProcEdit[8];
	char * msg_SegmentEdit[8];
	int	trigger_SegmentEdit;
	char * hint_SegmentEdit[8];
	char * msg_ProcInfo[8];
	char * hint_ProcInfo[8];
	int	value_ProcInfo;
	char * msg_SegmName[8];
	char * hint_SegmName[8];
	int	value_SegmName;
	char * msg_GlobNames[8];
	char * hint_GlobNames[8];
	int	value_GlobNames;
	char * msg_LocalNames[8];
	char * hint_LocalNames[8];
	int	value_LocalNames;
	char * msg_AssignList[8];
	char * hint_AssignList[8];
	int	value_AssignList;
	char * msg_RegisterList[8];
	char * hint_RegisterList[8];
	int	value_RegisterList;
	char * msg_AttachList[8];
	char * hint_AttachList[8];
	int	value_AttachList;
	char * msg_StackList[8];
	char * hint_StackList[8];
	int	value_StackList;
	char * msg_LibraryList[8];
	char * hint_LibraryList[8];
	int	value_LibraryList;
	char * msg_ObserveList[8];
	char * hint_ObserveList[8];
	int	value_ObserveList;
	char * msg_DeleteObservation[8];
	int	trigger_DeleteObservation;
	char * hint_DeleteObservation[8];
	char * msg_BreakList[8];
	char * hint_BreakList[8];
	int	value_BreakList;
	char * msg_RemoveBreak[8];
	int	trigger_RemoveBreak;
	char * hint_RemoveBreak[8];
	char * msg_ExportAssign[8];
	int	trigger_ExportAssign;
	char * hint_ExportAssign[8];
	char * msg_WatchList[8];
	char * hint_WatchList[8];
	int	value_WatchList;
	char * msg_DeleteWatch[8];
	int	trigger_DeleteWatch;
	char * hint_DeleteWatch[8];
	char * msg_SourceList[8];
	char * hint_SourceList[8];
	int	value_SourceList;
	char * msg_InspectSource[8];
	int	trigger_InspectSource;
	char * hint_InspectSource[8];
	char * hint_Syntax[8];
	char	buffer_Syntax[227];
	char * msg_Auto2916[8];
	char * hint_Auto2916[8];
	char * msg_auto6060[8];
	char * hint_auto6060[8];
	char * msg_Auto2917[8];
	char * hint_Auto2917[8];
	char * msg_Auto2918[8];
	char * hint_Auto2918[8];
	char * msg_Auto2919[8];
	char * hint_Auto2919[8];
	char * msg_Auto2920[8];
	char * hint_Auto2920[8];
	char * msg_Auto2921[8];
	char * hint_Auto2921[8];
	char * msg_auto6061[8];
	char * hint_auto6061[8];
	char * msg_auto6062[8];
	char * hint_auto6062[8];
	char * msg_auto6063[8];
	char * hint_auto6063[8];
	char * msg_auto6064[8];
	char * hint_auto6064[8];
	char * msg_AED_NORMAL[8];
	char * hint_AED_NORMAL[8];
	int	value_AED_NORMAL;
	char * msg_AED_QUOTE[8];
	char * hint_AED_QUOTE[8];
	int	value_AED_QUOTE;
	char * msg_AED_KEYWORD[8];
	char * hint_AED_KEYWORD[8];
	int	value_AED_KEYWORD;
	char * msg_AED_COMMENT[8];
	char * hint_AED_COMMENT[8];
	int	value_AED_COMMENT;
	char * msg_AED_PUNCTUATE[8];
	char * hint_AED_PUNCTUATE[8];
	int	value_AED_PUNCTUATE;
	char * msg_EditorColour[8];
	int	trigger_EditorColour;
	char * hint_EditorColour[8];
	char * msg_SetBreakAP[8];
	int	trigger_SetBreakAP;
	char * hint_SetBreakAP[8];
	char * msg_SetBreakBP[8];
	int	trigger_SetBreakBP;
	char * hint_SetBreakBP[8];
	char * msg_SetBreakAS[8];
	int	trigger_SetBreakAS;
	char * hint_SetBreakAS[8];
	char * msg_SetFileWatch[8];
	int	trigger_SetFileWatch;
	char * hint_SetFileWatch[8];
	char * msg_AllFileWatch[8];
	int	trigger_AllFileWatch;
	char * hint_AllFileWatch[8];
	char * msg_RazFileWatch[8];
	int	trigger_RazFileWatch;
	char * hint_RazFileWatch[8];
	char * msg_SetBreakBS[8];
	int	trigger_SetBreakBS;
	char * hint_SetBreakBS[8];
	char * msg_MultipleWatch[8];
	int	trigger_MultipleWatch;
	char * hint_MultipleWatch[8];
	char * msg_SingleWatch[8];
	int	trigger_SingleWatch;
	char * hint_SingleWatch[8];
	char * msg_ObserveGlobal[8];
	int	trigger_ObserveGlobal;
	char * hint_ObserveGlobal[8];
	char * msg_InspectGlobal[8];
	int	trigger_InspectGlobal;
	char * hint_InspectGlobal[8];
	char * msg_ObserveLocal[8];
	int	trigger_ObserveLocal;
	char * hint_ObserveLocal[8];
	char * msg_InspectLocal[8];
	int	trigger_InspectLocal;
	char * hint_InspectLocal[8];
	char * msg_VariableControl[8];
	int	trigger_VariableControl;
	char * hint_VariableControl[8];
	char * msg_Auto2922[8];
	char * hint_Auto2922[8];
	char * msg_vListe[8];
	char * hint_vListe[8];
	int	value_vListe;
	int	column_vListe;
	char	buffer_vListe[35][114];
	int	formsort_vListe;	/* sort 0 rien, positif numéro de colonne, négatif, numéro de colonne tri decroissant */
	char	*libsort_vListe;	/* table intermédiaire contenant la liste des éléments a trier */
	int	*tabsort_vListe;	/* numéro d'ordre des elements triés */
	char	*indsort_vListe;	/* pointeur table intermédiaire de tri */
	int	nelt_vListe;	/* nombre d'eléments aloués dans tabsort */
	char * row_vListe;
	char * hint_vBar[8];
	int	value_vBar;
	int	limit_vBar;
	int	max_vBar;
	char * hint_Auto2923[8];
	char * hint_StatusBar[8];
	char	buffer_StatusBar[120];
	char	signature[28];
	};

#endif /* _vexadb_h */
