! include $(ABAL)/common/criteria.def
! shell cd $(ABAL)/exmafl64; $(MAKE) -a 40
! ifdef BUILDEXMAFL16
! shell cd $(ABAL)/exmafl16; $(MAKE) -a 40
! endif
! ifdef BUILDEXMAFL32
! shell cd $(ABAL)/exmafl32; $(MAKE) -a 40
! endif

