$(ABAL)/src/tools32a/alphacode.xml: /home/abal3/tools/alphacode.xml
	cp $* $@
$(ABAL)/src/tools32a/alphanum.xml: /home/abal3/tools/alphanum.xml
	cp $* $@
$(ABAL)/src/tools32a/boitemess1.xml: /home/abal3/tools/boitemess1.xml
	cp $* $@
$(ABAL)/src/tools32a/boitemess2.xml: /home/abal3/tools/boitemess2.xml
	cp $* $@
$(ABAL)/src/tools32a/boitemess3.xml: /home/abal3/tools/boitemess3.xml
	cp $* $@
$(ABAL)/src/tools32a/calculator.xml: /home/abal3/tools/calculator.xml
	cp $* $@
$(ABAL)/src/tools32a/calendar.xml: /home/abal3/tools/calendar.xml
	cp $* $@
$(ABAL)/src/tools32a/character.xml: /home/abal3/tools/character.xml
	cp $* $@
$(ABAL)/src/tools32a/clavier.xml: /home/abal3/tools/clavier.xml
	cp $* $@
$(ABAL)/src/tools32a/copyfile.xml: /home/abal3/tools/copyfile.xml
	cp $* $@
$(ABAL)/src/tools32a/date.xml: /home/abal3/tools/date.xml
	cp $* $@
$(ABAL)/src/tools32a/datum.xml: /home/abal3/tools/datum.xml
	cp $* $@
$(ABAL)/src/tools32a/delfile.xml: /home/abal3/tools/delfile.xml
	cp $* $@
$(ABAL)/src/tools32a/directory.xml: /home/abal3/tools/directory.xml
	cp $* $@
$(ABAL)/src/tools32a/fichier.xml: /home/abal3/tools/fichier.xml
	cp $* $@
$(ABAL)/src/tools32a/filefinder.xml: /home/abal3/tools/filefinder.xml
	cp $* $@
$(ABAL)/src/tools32a/fileinfo.xml: /home/abal3/tools/fileinfo.xml
	cp $* $@
$(ABAL)/src/tools32a/filemenu.xml: /home/abal3/tools/filemenu.xml
	cp $* $@
$(ABAL)/src/tools32a/hexcode.xml: /home/abal3/tools/hexcode.xml
	cp $* $@
$(ABAL)/src/tools32a/hmenu.xml: /home/abal3/tools/hmenu.xml
	cp $* $@
$(ABAL)/src/tools32a/insee.xml: /home/abal3/tools/insee.xml:
	cp $* $@
$(ABAL)/src/tools32a/keyboard.xml: /home/abal3/tools/keyboard.xml
	cp $* $@
$(ABAL)/src/tools32a/menutest.xml: /home/abal3/tools/menutest.xml
	cp $* $@
$(ABAL)/src/tools32a/money.xml: /home/abal3/tools/money.xml
	cp $* $@
$(ABAL)/src/tools32a/montant.xml: /home/abal3/tools/montant.xml
	cp $* $@
$(ABAL)/src/tools32a/palette.xml: /home/abal3/tools/palette.xml
	cp $* $@
$(ABAL)/src/tools32a/pincode.xml: /home/abal3/tools/pincode.xml
	cp $* $@
$(ABAL)/src/tools32a/program.xml: /home/abal3/tools/program.xml
	cp $* $@
$(ABAL)/src/tools32a/renfile.xml: /home/abal3/tools/renfile.xml
	cp $* $@
$(ABAL)/src/tools32a/statusbar.xml: /home/abal3/tools/statusbar.xml
	cp $* $@
$(ABAL)/src/tools32a/telephone.xml: /home/abal3/tools/telephone.xml
	cp $* $@
$(ABAL)/src/tools32a/tierces.xml: /home/abal3/tools/tierces.xml
	cp $* $@
$(ABAL)/src/tools32a/toolbar.xml: /home/abal3/tools/toolbar.xml
	cp $* $@
$(ABAL)/src/tools32a/toolbase.xml: /home/abal3/tools/toolbase.xml
	cp $* $@
$(ABAL)/src/tools32a/toolman.xml: /home/abal3/tools/toolman.xml
	cp $* $@
$(ABAL)/src/tools32a/tools.xml: /home/abal3/tools/tools.xml
	cp $* $@
$(ABAL)/src/tools32a/villecp.xml: /home/abal3/tools/villecp.xml
	cp $* $@
$(ABAL)/src/tools32a/vmenu.xml: /home/abal3/tools/vmenu.xml
	cp $* $@
! make
$(ABAL)/src/tools32a/alphacode.gif: /home/abal3/tools/alphacode.gif
	cp $* $@
$(ABAL)/src/tools32a/alphanum.gif: /home/abal3/tools/alphanum.gif
	cp $* $@
$(ABAL)/src/tools32a/boitemess1.gif: /home/abal3/tools/boitemess1.gif
	cp $* $@
$(ABAL)/src/tools32a/boitemess2.gif: /home/abal3/tools/boitemess2.gif
	cp $* $@
$(ABAL)/src/tools32a/boitemess3.gif: /home/abal3/tools/boitemess3.gif
	cp $* $@
$(ABAL)/src/tools32a/calculator.gif: /home/abal3/tools/calculator.gif
	cp $* $@
$(ABAL)/src/tools32a/calendar.gif: /home/abal3/tools/calendar.gif
	cp $* $@
$(ABAL)/src/tools32a/character.gif: /home/abal3/tools/character.gif
	cp $* $@
$(ABAL)/src/tools32a/clavier.gif: /home/abal3/tools/clavier.gif
	cp $* $@
$(ABAL)/src/tools32a/copyfile.gif: /home/abal3/tools/copyfile.gif
	cp $* $@
$(ABAL)/src/tools32a/date.gif: /home/abal3/tools/date.gif
	cp $* $@
$(ABAL)/src/tools32a/datum.gif: /home/abal3/tools/datum.gif
	cp $* $@
$(ABAL)/src/tools32a/delfile.gif: /home/abal3/tools/delfile.gif
	cp $* $@
$(ABAL)/src/tools32a/directory.gif: /home/abal3/tools/directory.gif
	cp $* $@
$(ABAL)/src/tools32a/fichier.gif: /home/abal3/tools/fichier.gif
	cp $* $@
$(ABAL)/src/tools32a/filefinder.gif: /home/abal3/tools/filefinder.gif
	cp $* $@
$(ABAL)/src/tools32a/fileinfo.gif: /home/abal3/tools/fileinfo.gif
	cp $* $@
$(ABAL)/src/tools32a/filemenu.gif: /home/abal3/tools/filemenu.gif
	cp $* $@
$(ABAL)/src/tools32a/hexcode.gif: /home/abal3/tools/hexcode.gif
	cp $* $@
$(ABAL)/src/tools32a/hmenu.gif: /home/abal3/tools/hmenu.gif
	cp $* $@
$(ABAL)/src/tools32a/insee.gif: /home/abal3/tools/insee.gif:
	cp $* $@
$(ABAL)/src/tools32a/keyboard.gif: /home/abal3/tools/keyboard.gif
	cp $* $@
$(ABAL)/src/tools32a/menutest.gif: /home/abal3/tools/menutest.gif
	cp $* $@
$(ABAL)/src/tools32a/money.gif: /home/abal3/tools/money.gif
	cp $* $@
$(ABAL)/src/tools32a/montant.gif: /home/abal3/tools/montant.gif
	cp $* $@
$(ABAL)/src/tools32a/palette.gif: /home/abal3/tools/palette.gif
	cp $* $@
$(ABAL)/src/tools32a/pincode.gif: /home/abal3/tools/pincode.gif
	cp $* $@
$(ABAL)/src/tools32a/program.gif: /home/abal3/tools/program.gif
	cp $* $@
$(ABAL)/src/tools32a/renfile.gif: /home/abal3/tools/renfile.gif
	cp $* $@
$(ABAL)/src/tools32a/statusbar.gif: /home/abal3/tools/statusbar.gif
	cp $* $@
$(ABAL)/src/tools32a/telephone.gif: /home/abal3/tools/telephone.gif
	cp $* $@
$(ABAL)/src/tools32a/tierces.gif: /home/abal3/tools/tierces.gif
	cp $* $@
$(ABAL)/src/tools32a/toolbar.gif: /home/abal3/tools/toolbar.gif
	cp $* $@
$(ABAL)/src/tools32a/toolman.gif: /home/abal3/tools/toolman.gif
	cp $* $@
$(ABAL)/src/tools32a/villecp.gif: /home/abal3/tools/villecp.gif
	cp $* $@
$(ABAL)/src/tools32a/vmenu.gif: /home/abal3/tools/vmenu.gif
	cp $* $@
! make
$(ABAL)/src/tools32a/tools.css: /home/abal3/tools/tools.css
	cp $* $@
$(ABAL)/src/tools32a/menus.css: /home/abal3/tools/menus.css
	cp $* $@
$(ABAL)/src/tools32a/tools.htm: /home/abal3/tools/tools.htm
	cp $* $@
! make

