! include $(ABAL)/common/host.def
! include $(ABAL)/common/agr.def
! include $(ABAL)/common/allocate.def
! include $(ABAL)/common/common.def
! include $(ABAL)/common/libconv.def

SRC      = $(ABAL)/src/otr/
LIB      = /lib

! include otr.mf
! make
! include ctr.mf
! make
# include atc.mf
# make
# include jtr.mf
# make



