.as.at,.s.at:
	otr32 -m -v -I./ -x $*

demobd1.at: demobd1.s
demobd2.at: demobd2.s
demobd3.at: demobd3.s
demof.at: demof.s
demold.at: demold.s
demosm.at: demosm.s
gw.at: gw.as
qw.at: qw.as
t.at: t.as
tw.at: tw.as

! make


