EXALIB = /lib
! shell $(MAKE) bdanet demo
! shell $(MAKE) bdanet client $(EXALIB)/libprotb32.so
! shell $(MAKE) bdanet mono $(EXALIB)/libprotb32.so
! shell $(MAKE) bdanet multi $(EXALIB)/libprotb32.so


