< constants for abal xml instruction >

Const XML_READ%=/0060
Const XML_READ_VERSION%=/0061
Const XML_READ_CHARSET%=/0062
Const XML_READ_STYLE%=/0063

Const XML_WRITE%=/00A0
Const XML_WRITE_VERSION%=/00A1
Const XML_WRITE_CHARSET%=/00A2
Const XML_WRITE_STYLE%=/00A3

Const XML_OPEN%=1
Const XML_NAME%=2
Const XML_VALUE%=3
Const XML_CLOSE%=4
Const XML_TEXT%=5

< eof >

