! include $(ABAL)/common/host.def
! include $(ABAL)/common/agr.def
! include $(ABAL)/common/allocate.def
! include $(ABAL)/common/ixciconr.def
! include $(ABAL)/common/linbda.def
! include $(ABAL)/common/libpng.def

V666 = -DVERSION666


#
# file         : makefile
# description  : for the compilation of libsing library
# date         : 04/12/2007
# version      : 1.1a.0.01
# status       : provisionary
#

C    = .c
H    = .h
O    = .o
CC      = $(GCC) -c $(GDB) $(SYSPNG) $(CC_SHARED)
LD      = g++ -g -o
POBJ    =
OBJ     =

COMPILE = $(CC) -DUNIX -Dunix -DCPP_PRODUCT

!include libpixel.mf
!include libsing.mf
! make



